### ISSUE TITLE
Update on window scroll

### ISSUE THREAD

**Issue by romgrk** [nvim-treesitter/nvim-treesitter-context#1]
https://github.com/neovim/neovim/issues/4322
https://github.com/neovim/neovim/pull/13117

**Comment by smartding** [comment]
neovim/neovim#13117 isn't merged yet, I get a no such event (Scroll) error every time I open neovim after #5

**Comment by romgrk** [comment]
Sorry about that, can you confirm you're on the latest master? I committed a guard for non-existent autocmd [here](https://github.com/romgrk/nvim-treesitter-context/blob/master/lua/treesitter-context.lua#L57) right after merging the Scroll event, you might have pulled just at the wrong moment :/

**Comment by romgrk** [comment]
Sorry my bad, the guard wasn't working. `if value then` when value is `0` seems to run in lua.

**Comment by romgrk** [comment]
Name has changed from `Scroll` to `WinScrolled`, need to update the name on our side when https://github.com/neovim/neovim/pull/13117 is merged.
