### ISSUE TITLE
Always show context regardless of viewport

### ISSUE THREAD

**Issue by ThePrimeagen** [nvim-treesitter/nvim-treesitter-context#100]
Sort of related to #91 (near similar fix is my guess) but I would like to be able to have context always on. 

Reasoning:  Here is the legit the path I am on (some code I didn't write but I have to figure out ways to upgrade it) `ClassNameICannotMention#FunctionNameICannotMention#for#for#if#if#while#if#for#for#if#if`  # = separator for scope.

Simple ease of use would be to show the context always because the context gets so big that I occlude the context without it showing up constantly.

**Comment by ThePrimeagen** [comment]
Looks like this also is related to #80

**Comment by lewis6991** [comment]
Wouldn't it be better to just set max lines to a large value?

**Comment by lewis6991** [comment]
Is this a dup of #31?
