### ISSUE TITLE
dropping duplicates in display window

### ISSUE THREAD

**Issue by ThePrimeagen** [nvim-treesitter/nvim-treesitter-context#102]
As of now its pretty impossible to drop duplicates based on node id.  

The reason being is if we match the following:

```lua
patterns = {
    "else_clause",
    "if_statement",
}
```

in typescript an `else if` statement has both of those in a parent child relationship, so you will get 2 copies of the `else if ...`

A simple fix would be to not append to the list if the previous item is exactly the same.

Thoughts?

**Comment by lewis6991** [comment]
Sorry, I don't 100% understand the issue. Can you provide an example?

**Comment by Saecki** [comment]
This shouldn't be an issue anymore, since a context line is only added once even if there are multiple matches in it. At least I can't reproduce it.
