### ISSUE TITLE
Make popup window zindex configurable

### ISSUE THREAD

**Issue by b0o** [nvim-treesitter/nvim-treesitter-context#114]
It would be nice if the `zindex` option of `nvim_open_win()` was configurable through this plugin's options.

**Comment by b0o** [comment]
See this issue for debate on whether this option should be added: https://github.com/lewis6991/nvim-treesitter-context/issues/20

**Comment by romgrk** [comment]
Sounds good, let's wait on https://github.com/neovim/neovim/issues/18486

**Comment by lewis6991** [comment]
FWIW, I think we can add it since it's low effort and harmless, I just think the main issue is that our default value is wrong.

**Comment by romgrk** [comment]
Yeah sure. So for the default, `40` would be a good value?
