### ISSUE TITLE
Show inner context instead of outer

### ISSUE THREAD

**Issue by Saecki** [nvim-treesitter/nvim-treesitter-context#121]
A while ago and in the gif inside the readme, this plugin used to show the inner context when `max_lines` was set. Now for some reason in all the languages I've tested (`rust`, `lua`, `java`), the outer one is shown.

For example:
```rust
impl A {
    fn b(&self) {
        ...
    }
}
```
When inside the function `b`, the context shown is `impl A {` instead of `fn b(&self) {`

Was this change intentional? And if it is, could we add a config option to switch to the old behavior?

**Comment by lewis6991** [comment]
The change wasn't necessarily intentional.

PR welcome.
