### ISSUE TITLE
Issue #80 was introduced again: context won't be shown if the line is under context window

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-treesitter/nvim-treesitter-context#126]
After this commit https://github.com/nvim-treesitter/nvim-treesitter-context/commit/81116dc03abf35ca99c7910f9f779961042dea12, the issue https://github.com/nvim-treesitter/nvim-treesitter-context/issues/80 occurs again.

The issue is: the context of a line isn't appearing when the line is covered by the context floating window, and instead it appears only when the line is no longer in the window. This is the previous bug and had been fixed by the old commit (https://github.com/nvim-treesitter/nvim-treesitter-context/commit/c8b09b90d98c336478d2e212c865d42b0dd904bb). However, this commit brought it back again. 

Thank you very much.

**Comment by Saecki** [comment]
I'm the author of the commit that brought back the issue you're having, can you provide some code to reproduce your issue?

**Comment by rockyzhang24** [comment]
Hi @Saecki , you can see issue #80. Your commit removed the fixing code for that issue. I already have an idea to solve this. I will try it when I get home. Thank you 😊

**Comment by rockyzhang24** [comment]
Hi @Saecki , I saw your commit to fix it. Great and thank you. Regarding your previous proposal about showing outer scope or inner scope when `max_lines` is set, I think we can add an option for this by just adjusting a little piece of code. 

We don't need to stop the iteration when `lines > max_lines`, and instead, we iterate all nodes and insert them into `parent_matches`. Then we return the first `max_lines` counts of `parent_matches` if we set the option to outer_scopt, or the last `max_lines` counts of `parent _matches` if it is set to inner_scope. 

Any thoughts? Thank you so much.

**Comment by Saecki** [comment]
> Hi @Saecki , I saw your commit to fix it. Great and thank you. Regarding your previous proposal about showing outer scope or inner scope when `max_lines` is set, I think we can add an option for this by just adjusting a little piece of code.
> 
> We don't need to stop the iteration when `lines > max_lines`, and instead, we iterate all nodes and insert them into `parent_matches`. Then we return the first `max_lines` counts of `parent_matches` if we set the option to outer_scopt, or the last `max_lines` counts of `parent _matches` if it is set to inner_scope.
> 
> Any thoughts? Thank you so much.

That should work

**Comment by rockyzhang24** [comment]
Nice. Could you please try it and add it into your commit? 😊 I’m hiking outside and don’t have my laptop. Thank you.

**Comment by Saecki** [comment]
Yeah, I'll open another PR for that

**Comment by Saecki** [comment]
I just realized, that I just reverted the behavior again, so it does indeed make sense to include the option in the linked PR.
