### ISSUE TITLE
Register as treesitter module

### ISSUE THREAD

**Issue by asmodeus812** [nvim-treesitter/nvim-treesitter-context#129]
Hello, great work on that plugin, i was wondering if it can be registered as a tree sitter module, similar to other similar plugins which use tree sitter - e.g - https://github.com/JoosepAlviste/nvim-ts-context-commentstring/blob/main/lua/ts_context_commentstring.lua. Reasoning behind is most treesitter plugins allow this, to enable users to have a single point of entry for configuration through `nvim-treesitter.configs`

**Comment by romgrk** [comment]
I'm not super convinced about the usefulness of that, but if someone wants to make it happen I'm fine with it.

**Comment by asmodeus812** [comment]
Is there any downside to having it ?

**Comment by lewis6991** [comment]
Yes. Treesitter modules force plugins to adapt to the module interface and imposes restrictions due to that interface. It's also work someone has to do and maintain.

Regardless, even if there was no downside, that wouldn't justify implementing it.

**Comment by lewis6991** [comment]
I think we'll pass on this. Even the maintainers of nvim-treesitter agree that modules are not designed well.
