### ISSUE TITLE
Documentation `line_numbers`

### ISSUE THREAD

**Issue by jrwrigh** [nvim-treesitter/nvim-treesitter-context#136]
README mentions a `line_numbers` option at the end, but there's no other reference to it. Possibly an undocumented option?

**Comment by romgrk** [comment]
Seems to have been added by https://github.com/nvim-treesitter/nvim-treesitter-context/pull/89 but it has been lost when we merged back the fork, is that possible @lewis6991? I will re-open that PR and merge it, sounds good?

**Comment by lewis6991** [comment]
Sounds good to me
