### ISSUE TITLE
Outer-most context linewraps over inner contexts

### ISSUE THREAD

**Issue by jrwrigh** [nvim-treesitter/nvim-treesitter-context#138]
If I have a function:
```c
PetscErrorCode CreateOperatorForDomain(Ceed ceed, DM dm, SimpleBC bc,
                                       CeedData ceed_data, Physics phys,
                                       CeedOperator op_apply_vol,
                                       CeedOperator op_apply_ijacobian_vol,
                                       CeedInt height,
                                       CeedInt P_sur, CeedInt Q_sur,
                                       CeedInt q_data_size_sur, CeedInt jac_data_size_sur,
                                       CeedOperator *op_apply, CeedOperator *op_apply_ijacobian) {
//[..........]
  if (phys->has_neumann || 1) {
    // --- Setup
    ierr = DMGetLabel(dm, "Face Sets", &domain_label); CHKERRQ(ierr);

    // --- Get number of quadrature points for the boundaries
    CeedInt num_qpts_sur;
    CeedBasisGetNumQuadraturePoints(ceed_data->basis_q_sur, &num_qpts_sur);

    // --- Create Sub-Operator for inflow boundaries
    for (CeedInt i=0; i < bc->num_inflow; i++) {
      CeedVector          q_data_sur, jac_data_sur;
      CeedOperator        op_setup_sur, op_apply_inflow,
                          op_apply_inflow_jacobian = NULL;
      CeedElemRestriction elem_restr_x_sur, elem_restr_q_sur, elem_restr_qd_i_sur,
                          elem_restr_jd_i_sur;
```
it'll show the context as:
![image](https://user-images.githubusercontent.com/20801821/176042233-3ab2947b-e846-4010-aac3-4bbe1ea4ace2.png)
So the function is wrapped into one line, but then cutoff because it's too long. Perfectly fine.

If I move past the `if` statement, I see:
![image](https://user-images.githubusercontent.com/20801821/176042363-a53eef00-a267-4652-a9ba-8c347cf5c0e1.png)
So the excess of the function signature context has now been wrapped onto the next context line. Note that the line number for the `if` context is correct, but it's not showing the correct one. Note that the function signature still isn't complete...

Continuing to move past the `for` loop, I see:
![image](https://user-images.githubusercontent.com/20801821/176043012-2b0fefa5-805c-40ae-aae4-f607a6a79f8a.png)
So now the function signature been wrapped over-top of both the `if` and `for` statements. Not ideal.

If I expand the width of the screen such that the function signature context can fit on two lines, I get:
![image](https://user-images.githubusercontent.com/20801821/176043549-79b3de00-c2d4-4845-8840-eb18054de46b.png)
Where the `if` context is now there and the line number next to it is incorrect (that's for the `for` context).

This seems to be an intended consequence of the patch that closes #10. Or perhaps an overlooked issue when making the patch for that.

I think the less annoying solution is just to keep each context limiited to it's own line. Being able to see the full context line would be nice, but not in exchange of not being able to see the other contexts.

**Comment by romgrk** [comment]
I can't reproduce but I've added a PR to explicitly set the `nowrap` option, but now that I think it might not be the wrapping. Would you mind testing that branch? Also could you share you config, if there is any, and the full file there?

**Comment by jrwrigh** [comment]
I tested out the branch, but the issue is still present. Let me try and push up my dotfiles real quick. The file/function in question is here: https://github.com/CEED/libCEED/blob/6e1e594c1a1c9083662b4f212401e3d6898dccad/examples/fluids/src/setuplibceed.c#L77, but I've encountered the problem consistently whenever the top-level context is forced to be cutoff.

**Comment by jrwrigh** [comment]
Here's the dotfiles repo: https://github.com/jrwrigh/dotfiles2.0/tree/fermat-initlua/.config/nvim

**Comment by jrwrigh** [comment]
Here's a more minimal config that I was able to reproduce the issue with:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      { 'nvim-treesitter/nvim-treesitter', config = function()
            require('nvim-treesitter.configs').setup {
              ensure_installed = {'c', 'python', 'fortran', 'bash', 'lua', 'vim', 'cpp'},
              highlight = {
                enable = true, -- false will disable the whole extension
              },
            }
            end
},
    { 'nvim-treesitter/nvim-treesitter-context', config=function() require('treesitter-context').setup() end}
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

(partially stolen from telescope's issue submission)

**Comment by jrwrigh** [comment]
Not sure what was wrong with my previous test, but that branch is working fine now!

**Comment by jrwrigh** [comment]
@grimgort I'd open up a  new issue. I haven't seen these problems, so it's likely a different root cause.

**Comment by grimgort** [comment]
> @grimgort I'd open up a new issue. I haven't seen these problems, so it's likely a different root cause.

Thanks !  I look forward to the correction :)
