### ISSUE TITLE
float snippet hover on the wrong when opening the CocList(plugin coc.nvim)

### ISSUE THREAD

**Issue by gpncarl** [nvim-treesitter/nvim-treesitter-context#14]
<img width="452" alt="截屏2020-10-27 下午1 23 52" src="https://user-images.githubusercontent.com/38633718/97260592-1301b600-1858-11eb-8052-ef90b0c6835a.png">

**Comment by romgrk** [comment]
Yes, the plugin is probably splitting the window first, then changing the buffer. We need to call update() on BufEnter autocmd.

**Comment by romgrk** [comment]
It should work now, please re-open if it persists.

**Comment by GPN211314** [comment]
same problem again, when using 'q/' or 'q:' to open a Command-line windows

<img width="354" alt="截屏2021-09-11 下午12 59 47" src="https://user-images.githubusercontent.com/38633718/132936938-c045ea7d-97d7-4782-911c-5dc20541900d.png">
