### ISSUE TITLE
Dockerfile build stage

### ISSUE THREAD

**Issue by phistep** [nvim-treesitter/nvim-treesitter-context#144]
Treesitter supports Dockerfile (`:TSInstall dockerfile`), and it would be nice to have the current build stage `FROM ... AS ...` as the floating context.
I tried adding `'from'` or `'FROM'` to `setup.patterns.default` (should probably go into `setup.patterns.dockerfile`), but it didn't work.

I don't know how to find the name of a node, so it might be helpful to add this to the readme next to the "open a PR" comment.

**Comment by phistep** [comment]
Another thing that I would like is goals/targets in Makefiles. I'm not going to open another issue for that rn, if you can help me find names of nodes, I'll just add PRs directly.

**Comment by romgrk** [comment]
You can use https://github.com/nvim-treesitter/playground to find the node names.

**Comment by lewis6991** [comment]
Supported languages are now tracked in the README.
