### ISSUE TITLE
Context window should inherit tabstop

### ISSUE THREAD

**Issue by CertainLach** [nvim-treesitter/nvim-treesitter-context#146]
Tabstops (I use `\t` for indents) are shown as 8 in the context window, while I configure the code window to use `tabstop=4`
![image](https://user-images.githubusercontent.com/6235312/180650298-0a200a8a-86f7-4aeb-af0a-95273ce1a21a.png)

Setting tabstop while the window is already open doesn't affect tabstops in the context window too

**Comment by lewis6991** [comment]
Fixes in #162
