### ISSUE TITLE
Appears to do nothing with shade.nvim

### ISSUE THREAD

**Issue by gdonald** [nvim-treesitter/nvim-treesitter-context#150]
```
> nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

Using `vim-plug`.

Tried `TSContextEnable` and `TSContextToggle`.

No errors, but nothing like the animation occurs when I scroll through a long Ruby, Javascript, or vim file.

**Comment by jayroh** [comment]
Similar to @gdonald, however in ruby files it will "work" pinning the context of a "class" in a ruby file at the top.

I'm reading through the source and trying to grok how to configure this to work with ruby filetypes but haven't quite got it.

Question, I guess, is:  if a filetype isn't included or accounted for in the plugin, can it be configured to work _anyway_?

**Comment by linduxed** [comment]
I have the same problem as @gdonald, with the same output from `nvim --version`.

**Comment by lewis6991** [comment]
If you can provide a testcase of the form:

```lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require'treesitter-context'.setup {}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

With: `nvim --clean -u min.lua`

Then I can take a look.

**Comment by aurum77** [comment]
So I've been having the same problem and decided to toy around with my config for a while (took like 30 minutes at most tbf) and found out that [shade.nvim](https://github.com/sunjon/Shade.nvim) was the culprit 🙀 (at least for me, when I took a glance at the dotfiles of others who had this problem, they didn't have shade.nvim) here's 
nvim --version:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```
test case:
```lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
  -- I've installed treesitter plugin because i didn't have treesitter
  -- on my system and so far I've tested it with javascript and c parsers
  ts = 'https://github.com/nvim-treesitter/nvim-treesitter',
  shade = 'https://github.com/sunjon/Shade.nvim' -- the culprit 🙀 
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require'treesitter-context'.setup {}
-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
require'shade'.setup({ -- the culprit 🙀 
	overlay_opacity = 75,
})
```
I'm gonna stop using shade.nvim because it's mostly eye candy 🤠

**Comment by LJ-Software** [comment]
I can confirm that like @aurum77 reported, disabling shade.nvim fixed the issue for me.

**Comment by linduxed** [comment]
I do not have `shade.nvim` installed, so I'll have to investigate which plugins I'll have to disable to figure out what could be causing the issue for me.

**Comment by rbutera** [comment]
doesn't work for me either using AstroNvim and neovim 0.7

Sad, because I really want this plugin to work, it looks awesome

**Comment by lewis6991** [comment]
Please see: https://github.com/nvim-treesitter/nvim-treesitter-context/issues/150#issuecomment-1214958638

**Comment by rbutera** [comment]
> Please see: [#150 (comment)](https://github.com/nvim-treesitter/nvim-treesitter-context/issues/150#issuecomment-1214958638)

I'm sorry, but I'm not sure what minimal init.lua settings to add to the testcase, as I am using AstroNvim (a popular neovim config distribution) and nvim-treesitter-context doesn't work even if it is the only custom plugin that I use

For reference, my user `init.lua` is [here](https://github.com/rbutera/dotfiles/blob/main/dot_config/nvim/lua/user/init.lua).

Sorry to not be able to provide more helpful information, I have only been using neovim as my main editor for about a month now.

**Comment by con-f-use** [comment]
Have the same problem, no shade.nvim installed.

**Comment by lewis6991** [comment]
People please stop reporting the issue unless you can provide a testcase.

**Comment by con-f-use** [comment]
Okay, I added more information to my comment. I also find your behavior here a bit unprofessional. Marking innocent comments as spam and disgruntling your user-base is not a good look.

**Comment by lewis6991** [comment]
Let me remind everyone the work provided here is FREE! I don't get paid for this, and I have other uses of my time which includes many other plugins in addition to Neovim core.

I've state and reiterated what Is required to move the issue further, I can't be more clear about that. If that can't be provided then please don't comment. It's either that, or I simply ignore this issue all together. I don't have the bandwidth to investigate niche problems with users configurations that may or may not turn out to be an issue with this plugin.

And let me finish by saying anybody here is very welcome to fix this issue themselves and submit a PR. It's certainly easier to fix an issue if you can reproduce it.

**Comment by con-f-use** [comment]
I'd be happy to sponsor you. I'm thankful that you provide a free service (that unfortunately doesn't work for me), however that doesn't make it okay to vent your frustration at well-meaning people.

**Comment by madlep** [comment]
Just wondering if it might make sense to have some kind of warning, or other output if no patterns are found for a given file, and nvim-treesitter-context can't do anything with it.

I installed, and ran into a vague _"not working"_ issue with Elixir source code. Checked here, and this issue was first thing I ran into to trouble shoot.

After some digging around, turned out it was just that the patterns that Elixir treesitter returns aren't picked up with the default config. After adding them, it works fine (added PR at https://github.com/nvim-treesitter/nvim-treesitter-context/pull/158 to add them to defaults).

But some message or warning or health check etc could make it easier for folks to debug and resolve without adding noise here 🙂.

**Comment by lincheney** [comment]
I can reproduce the issue with shade.nvim (same as others here).

The problem is due to shade.nvim putting a floating window on top of the buffer with a higher zindex than the treesitter context window, so it gets covered.
If you configure the treesitter context zindex to be higher, then it will appear.
I suggest people try that.

**Comment by con-f-use** [comment]
@lincheney , care to drop a line or two as how one would configure that?

**Comment by lincheney** [comment]
Yeah that should be it.
If it is not working, maybe check `:echo getwininfo()`
When it activates, there should be two treesitter context windows in there (one for the content, one for the line numbers).

**Comment by gegoune** [comment]
shade.nvim seems pretty unmaintained and never really worked for me, I have encountered number of issues with it.

Try replacing it with [tint.nvim](https://github.com/levouh/tint.nvim).

**Comment by con-f-use** [comment]
![image](https://user-images.githubusercontent.com/11145016/197736780-aadeebf4-f3e4-4464-9450-156009d9870c.png)

how so?

**Comment by lewis6991** [comment]
This is an issue with shade.nvim and the solution is to just adjust z-index of either plugin.

**Comment by con-f-use** [comment]
For me it doesn't seem to be, but okay, I'll figure something.

**Comment by gabevenberg** [comment]
> For me it doesn't seem to be, which leads me to believe it isn't for others. But okay, I'll figure something. Again, thanks for the effort and sharing. From what I can tell I'm having some weird interaction between bufferline, lualine and treesitter-context. Because if I disable either of the two *lines the latter works and zindex doesn't seem to do anything. So it's not just shade.

Did you ever figure this out? I tried removing tabline and bufferline, as well as messing with the z-index. No luck.

**Comment by Momijiichigo** [comment]
For me, it does not work even when there is no other plugins:
```
> nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
```lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
  ts = 'https://github.com/nvim-treesitter/nvim-treesitter',

}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require'treesitter-context'.setup{ }

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

Tried z-index but did not work either.
(I use Manjaro Linux x86_64)

**Comment by cblessing24** [comment]
I also could not get it working with the minimal config but then I realized I had to probably install the parser for the filetype I was looking at. After that it worked with the minimal config. So to everyone that can't get it working with the minimal config make sure the correct **parser is installed**.

**Comment by con-f-use** [comment]
parser?

**Comment by cblessing24** [comment]
Yes, you have to install the parser for your filetype. For example to install it for lua you can run `:TSInstall lua` or like this in your config file:
```lua
require("nvim-treesitter.configs").setup({ ensure_installed = { "lua" } })
```
Maybe it would be worthwhile to mention this in the README because people that have not used treesitter outside this plugin will not know they have to install a parser.

**Comment by con-f-use** [comment]
yeah, no. that's not it.
