### ISSUE TITLE
Can I integrate this feature to telescope preview?

### ISSUE THREAD

**Issue by DanielK20222** [nvim-treesitter/nvim-treesitter-context#154]
Thanks for sharing this nice feature, I'm really enjoying it. One request or maybe question, 

Can I integrate this context feature on the telescope preview window? It would be really nice to be able to use this on it.

**Comment by przepompownia** [comment]
nvim-bqf is another example. 
![image](https://user-images.githubusercontent.com/11404453/190916597-46708b6e-1bd7-443f-a50e-883e55ddbfd5.png)

Maybe I am wrong: it seems that the plugin needs some changes to support windows other than the current.

**Comment by lewis6991** [comment]
Closing this, but will accept a PR.
