### ISSUE TITLE
csharp: context shows attributes instead of class/method names, obscuring context detail

### ISSUE THREAD

**Issue by cptchuckles** [nvim-treesitter/nvim-treesitter-context#160]
In an example C# source file, i have:
```cs
/*    using statements     */

[ApiController]
[Route("api/")]
public class AuthController : ControllerBase
{
    /*    constructor etc.    */

    [AllowAnonymous]
    [HttpPost("Register")]
    public async Task<ActionResult<string>> Register([FromBody] UserRegisterDto request)
    {
        if (await _context.Users.AnyAsync(u => u.Email.ToLower() == request.Email.ToLower()))
            return BadRequest($"User with email {request.Email} already exists");
        if (await _context.Users.AnyAsync(u => u.Username.ToLower() == request.Username.ToLower()))
            return BadRequest($"Username {request.Username} already exists");

        var user = new User(request.Username, request.Email, request.Password);
```
But observe how the context looks like:
![treesitter context shows attributes](https://i.imgur.com/HTYmx9Y.png)

I would prefer if it showed like:
```cs
public class AuthController : ControllerBase
    public async Task<ActionResult<string>> Register([FromBody] UserREgisterDto request)
------------------------------------------------------------------------------------------------------------
```

I assume I should be able to configure it to ignore attributes in `cs` filetype buffers, but the readme doesn't go into enough detail for me to work out how to exclude things like that.

**Comment by cptchuckles** [comment]
I looked in the code and found a reference to `userOptions.exclude_patterns`, so i tried the following to no avail:
```lua
require('treesitter-context').setup({
    exclude_patterns = {
        cs = {
            'attribute_list',
            'attribute',
        },
    },
})
```

**Comment by cptchuckles** [comment]
It's probably happening because treesitter nests the attributes under the `class_declaration`, and the `class_declaration` starts on the line with the first attribute.  The playground shows that the `class_declaration` starts on line 11, but the `name: identifier` for the actual class is on line 13.
```
  class_declaration [11, 0] - [108, 1]
    attribute_list [11, 0] - [11, 15]
      attribute [11, 1] - [11, 14]
        name: identifier [11, 1] - [11, 14]
    attribute_list [12, 0] - [12, 15]
      attribute [12, 1] - [12, 14]
        name: identifier [12, 1] - [12, 6]
        attribute_argument_list [12, 6] - [12, 14]
          attribute_argument [12, 7] - [12, 13]
            string_literal [12, 7] - [12, 13]
    modifier [13, 0] - [13, 6]
    name: identifier [13, 13] - [13, 27]
    bases: base_list [13, 28] - [13, 44]
      identifier [13, 30] - [13, 44]
    body: declaration_list [14, 0] - [108, 1]
```
so I'm doubtful that this is going to be trivial now, unless there's some way I can exclude `class_declaration` yet *include* `class_declaration.name`, or something.  I've tried a few ways, but if i exclude `class_declaration` then I get nothing.

**Comment by Saecki** [comment]
There already is the `skip_leading_types` table, which does exactly what is needed here. In my fork I just restructured the way things are declared. Adding another entry should to the trick.

**Comment by lewis6991** [comment]
#198 C sharp is no longer supported and the information in this thread is no longer useful. Will happily accept a PR that adds a query for C sharp.

**Comment by whitebyte** [comment]
Since C# is back, can this issue be reopen? It's still relevant

**Comment by lewis6991** [comment]
No we don't track issues for individual languages as they are community maintained. In other words: If there's an issue you want fixed then _you_ need to fix it.
