### ISSUE TITLE
Highlight relevant rows that are still on screen

### ISSUE THREAD

**Issue by Masterhigure** [nvim-treesitter/nvim-treesitter-context#169]
Some times you are inside a block where the top of the block is still on screen. I would very much like the possibility to highlight those lines as well, just like the lines that are technically off-screen which this plugin brings back on-screen glued to the top. Whether that's best accessed through an option in the settings or through a separate (by default empty) highlighting group I don't know.

This is of course only relevant when `mode = 'cursor'`.

**Comment by lewis6991** [comment]
I think we will pass on this. Thanks for the suggestion though.
