### ISSUE TITLE
[HELP] how to disable context for certain filetype and enable for other?

### ISSUE THREAD

**Issue by dhruvinsh** [nvim-treesitter/nvim-treesitter-context#172]
Hi,
I have a use case wehre I would like to disable treesitter-context but enable for all others, is it possible to do so?

**Comment by romgrk** [comment]
It is not, but we could add a feature to do so, when we find time. PR welcome as well.

**Comment by dhruvinsh** [comment]
just open a pull requests: https://github.com/nvim-treesitter/nvim-treesitter-context/pull/175

**Comment by metasyn** [comment]
I would also benefit from this feature, as I found an issue where the nvim-treesitter-context crashes for certain filetypes, and would like to automatically turn it off rather than manually turning it off each time.

**Comment by tjdevries** [comment]
I think you can do something like this:

```lua
vim.treesitter.query.set("lua", "context", "")
```

to disable for certain languages

**Comment by ColinKennedy** [comment]
@tjdevries that's pretty good! I'm in the opposite camp though, I only want this to be enabled for one or two languages and disabled on all others. I could defer the plug-in just for that one or two file types:

```lua
{
    "nvim-treesitter/nvim-treesitter-context",
    dependencies = {"nvim-treesitter/nvim-treesitter"},
    ft = "file_type_i_want_it_on",
},
```

but the moment I visit the filetype(s) which I don't want it for, it will apply there too. I'm getting around it by querying all parsers in a loop and disabling them with `vim.treesitter.query.set(name, "context", "")` but a more robust solution would be nice.

**Comment by utkarshgupta137** [comment]
@lewis6991 Can you share a sample on_attach function for disabling this plugin for markdown files only?

**Comment by lewis6991** [comment]
```lua
        on_attach = function()
          return vim.bo.filetype ~= 'markdown'
        end
```
