### ISSUE TITLE
Treesitter context Visual selection bug

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-treesitter/nvim-treesitter-context#176]
Enable tree-sitter context on the below file.

Edit the file and type the following:
1. `G`
    Go to the bottom of the file. Ensure treesitter-context is showing the context at the top line of the buffer.
2. `V12k`
    Create a visual selection. 

The visual selection skips the 10 lines between the top and bottom visually selected lines instead of showing on all of the lines.

```lua
def func() -> None:
    """







































    """
    print()

```

**Comment by lewis6991** [comment]
Are you sure this is a problem with this plugin and not neovim core?

**Comment by lewis6991** [comment]
https://github.com/neovim/neovim/pull/20665 might fix this.

**Comment by barrett-ruth** [comment]
Fixed. Thanks for your consistent work lewis!
