### ISSUE TITLE
Visual Mode rendering issue 

### ISSUE THREAD

**Issue by kwie98** [nvim-treesitter/nvim-treesitter-context#180]
Since 2f9f75d33158c0289c70cc1e0975af9d36ec16b2, it seems that there is a rendering issue with visual selections. Specifically, I noticed this when using https://github.com/nvim-treesitter/nvim-treesitter-textobjects to select around a whole function that takes up more space than what can be rendered at once. This is how the selection should look:
![image](https://user-images.githubusercontent.com/35312155/197331746-5307836c-9f48-43d0-a849-857f80bf2994.png)
Instead, this is what I get after opening the file, going to line 70 (`:70`) and pressing `vam` to select the whole function:
![image](https://user-images.githubusercontent.com/35312155/197331802-0663c87d-f099-41ef-8b79-6ff5b05fb4f5.png)
If I press `o` twice, the graphical glitch disappears and it looks right again, but that's no fun!

I've been able to reproduce this in a minimal config and with that rather minimal `sample.py` file you see in the pictures above. Sadly I did not get the config 100% perfect, you'll have to restart neovim after loading it for the first time and then install the python parser for the sample file with `:TSInstall`.

Minimal Config:
```lua
local fn = vim.fn
vim.opt.expandtab = true
vim.opt.shiftwidth = 4

-- Automatically install packer
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    PACKER_BOOTSTRAP = fn.system({
        "git",
        "clone",
        "--depth",
        "1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    })
    print("Installing packer close and reopen Neovim...")
    vim.cmd([[packadd packer.nvim]])
end

-- Use a protected call so we don't error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
    print("Could not load packer.")
    return
end

-- Have packer use a popup window
packer.init({
    display = {
        open_fn = function()
            return require("packer.util").float()
        end,
    },
})

packer.startup(function(use)
    use({ "wbthomason/packer.nvim" }) -- Have packer manage itself
    -- Treesitter
    use({
        "nvim-treesitter/nvim-treesitter",
        commit = "c4c358e9badb181f4a05a4d8fd0c986a1cf5001b",
    })
    use({
        "nvim-treesitter/nvim-treesitter-context",
        commit = "2f9f75d33158c0289c70cc1e0975af9d36ec16b2", -- bug from here on out
        -- commit = "c46a8a0a60412a8fe43aa6bd3a01845c46de6bf2", -- no bug on this commit
    })
    use({
        "nvim-treesitter/nvim-treesitter-textobjects",
        commit = "13739a5705d9592cbe7da372576363dc8ea5f723",
    })

    -- Automatically set up your configuration after cloning packer.nvim
    -- Put this at the end after all plugins
    if PACKER_BOOTSTRAP then
        require("packer").sync()
    end
end)
require("treesitter-context").setup()
require("nvim-treesitter.configs").setup({
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["am"] = "@function.outer",
            },
        },
    },
})
```

And that sample code file to reproduce the issue:
```python
def pi_func():
    while True:
        def pi(S, is_training):

            # directly map state to actions
            pass

            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass

            pass
            pass
            pass
            pass
            pass
            pass
            pass

            pass
            pass
            pass
            pass

            pass
            pass
            pass
            pass

            pass
            pass
            pass
            pass
            pass
            pass
            pass
            pass

            return {"mu": mu, "logvar": logvar}
        pass
        pass
        pass
        pass
        pass
        pass
        pass

        pass
        pass
        pass
        pass
        pass
        pass
        pass
        pass
        pass
        pass
        pass
        pass
    return pi
```

**Comment by thisisrandy** [comment]
I'm also seeing this behavior, but it presents in a slightly different way than OP describes. The issue doesn't seem to be selecting a long function so much as selecting anything, including a short block, while context is being displayed. In the following, I use `vip` at the top of a long function and see that it is correctly selected. Then, I use `vip` on a short block near the bottom of that function with context displayed and observe that the selection display is broken.

![Peek 2022-10-27 13-20](https://user-images.githubusercontent.com/22106562/198390491-858f9675-46ae-4448-891d-017b3b313a02.gif)

**Comment by lewis6991** [comment]
@thisisrandy have you checked with the latest build? The already mentioned fixes apply for various situations.

**Comment by pranavpa8788** [comment]
@lewis6991 I'm running the latest 0dd5eae commit version and still experiencing this glitch

**Comment by lewis6991** [comment]
Ok, please raise a new issue with reproducible steps.

**Comment by lewis6991** [comment]
Sorry, I didn't mention (got confused which repo this issue was in).

I believe this is an issue with Neovim core. Can everyone please try the latest dev build of Neovim.

**Comment by thisisrandy** [comment]
@lewis6991 I just tried with `NVIM v0.9.0-dev-184+g685ff3ee7`, and it appears you are correct. I was on stable (`NVIM v0.8.0-1210-gd367ed9b2`) previously. Any chance you can point to the specific issue that's since been fixed?

**Comment by kwie98** [comment]
Weirdly enough, 0dd5eae6dbf226107da2c2041ffbb695d9e267c1 does seem to fix the issue I had; at least I can't reproduce it as before. This is with the same neovim version as before too, `NVIM v0.8.0`.

And with `NVIM v0.9.0-dev-198+g75ec1b720`, I can't even reproduce on 09455f941a1611666a6343f68b97dd0a12d4c846 which was broken for me, before.

I'll mark this as closed as I think the situation is resolved with this.
