### ISSUE TITLE
unexpected lines comes up

### ISSUE THREAD

**Issue by srillia** [nvim-treesitter/nvim-treesitter-context#182]
### neovim  version
:version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.8.0/share/nvim"
### nvim-treesitter-context context version 
[09455f9](https://github.com/nvim-treesitter/nvim-treesitter-context/commit/09455f941a1611666a6343f68b97dd0a12d4c846)

### problems

When set vim.opt.relativenumber = true,
![image](https://user-images.githubusercontent.com/25891673/197686005-b4bb42b4-1d76-4864-b837-fb079d77138e.png)

unexpected lines comes up , expected one ,but repeat more lines

**Comment by lewis6991** [comment]
Please provide more information on how to reproduce

**Comment by samb233** [comment]
I have the same bug about a month ago.  When scroll to the end of file and the last function is longer then a page.

But after some plugin update, now I can't reproduce this bug either. Tested on nvim0.8.1, treesitter [4b2cd22](https://github.com/nvim-treesitter/nvim-treesitter/commit/4b2cd221beb76784abe6a70da2eb53d7b67aebac), treesitter-context  [5fda0b9](https://github.com/nvim-treesitter/nvim-treesitter-context/commit/5fda0b9a2a9049ecc9900e2d86d9ddebab95b0c5)
