### ISSUE TITLE
treesitter query.lua and context error while processing CursorMoved

### ISSUE THREAD

**Issue by webmandman** [nvim-treesitter/nvim-treesitter-context#186]
neovim version: v0.8.0-v.0.8.0
build type: Release

![2022-11-09-063300_1584x519_scrot](https://user-images.githubusercontent.com/991677/200858292-dc84db15-1eed-499b-a2b8-95c65f781eea.png)

I've tried :TSUpdateSync but when I select words with SHIFT+8 this error occurs and same occurs when I use n or  p to move to the next or prev match.

When I disable context with :TSContextDisable I can move the cursor around without error.

**Comment by lewis6991** [comment]
This looks unrelated to this plugin. The error is coming from an outdated query.

**Comment by marco-silva0000** [comment]
@webmandman how did you fix this? I'm having the exact same issue

**Comment by lewis6991** [comment]
Update your treesitter plugins and/or your Neovim version.

**Comment by marco-silva0000** [comment]
I had everything up to date, turned out to be this: https://github.com/nvim-treesitter/nvim-treesitter-angular/issues/3

using the latest comment there fixed it for me. Ty for the quick reply @lewis6991
