### ISSUE TITLE
Support to co-work with ts hightlight variable？

### ISSUE THREAD

**Issue by xaljer** [nvim-treesitter/nvim-treesitter-context#19]
nvim-treesitter has the feature of highlighting where a symbol is defined. Could make it also works on the context header?

**Comment by romgrk** [comment]
You'd like the context header to show where a symbol is defined, when the cursor is on that symbol? Feels slightly out of scope for this plugin, it would fit better in a plugin that shows previews/definitions.

**Comment by xaljer** [comment]
I mean that highlighting the parameter in a function prototype showing by context header, if current cursor is on where the parameter is used in the function. 

int foo(int a, int b)    <- show by context header. highlight the 'a' just like this line is in range of screen instead of context.
    ....
    a = 3;                    <- cursor on symbol 'a'
}
