### ISSUE TITLE
Is there a way to jump to the begin line of the context? kinda like `gg` jump to the first line. 

### ISSUE THREAD

**Issue by gh-liu** [nvim-treesitter/nvim-treesitter-context#190]

**Comment by lewis6991** [comment]
No not currently

**Comment by romgrk** [comment]
Wouldn't be too hard to add if we merge #143.

**Comment by lewis6991** [comment]
Line numbers are now included in the contexts.

**Comment by alisnic** [comment]
@lewis6991 can you expand on that? maybe a short example how to write a keybind to jump to context?

**Comment by lewis6991** [comment]
`<line number>gg`

**Comment by alisnic** [comment]
I get the irony here, and that's exactly how I jump right now. However, it would be a lot faster to have a motion to jump to previous context, similarly to `[m`. The latter however does not have the behavior I want. The end-goal is to have something like "jump out of context"

**Comment by lewis6991** [comment]
Currently that isn't possible. Would accept a PR.
