### ISSUE TITLE
Trying to add `access_specifier` as context

### ISSUE THREAD

**Issue by galou** [nvim-treesitter/nvim-treesitter-context#217]
I wanted to add `public:`, `protected:`, `private:` as context in class declaration but didn't manage to have it work.
 
I added `(access_specifier) @context` to `queries/cpp/context.scm` but this has no effect.

Can nvim-treesitter-context support this?

**Comment by galou** [comment]
```cpp
class MyClass
{
public:
  MyClass();

  void myPublicFunction();

private:
  int my_member_;
};
```

**Comment by amaanq** [comment]
Don't think it's possible since access_specifier is a sibling node to field members, not a parent of those
