### ISSUE TITLE
TypeScript and JavaScript function expressions

### ISSUE THREAD

**Issue by topaxi** [nvim-treesitter/nvim-treesitter-context#218]
### Description

TypeScript and JavaScript function expressions do not create a new context.

### Neovim version

NVIM v0.8.3

### Expected behavior

The following function declarations should create a context:

```ts
let myfn = function() {
  // ...body...
};

let myfn = () => {
  // ...body...
};

window.addEventListener('click', () => {
  // ...body...
});

// ...etc...
```

### Actual behavior

Only "normal" function declarations create a context.

**Comment by lewis6991** [comment]
PR welcome
