### ISSUE TITLE
Disable/enable context nodes by type/kind

### ISSUE THREAD

**Issue by Saecki** [nvim-treesitter/nvim-treesitter-context#223]
It would be great if there would be some way to enable or disable only some types/kinds of context nodes, ideally in a language agnostic way. For example I like contexts for `struct`s `class`es or `function`s but dislike them for `if` statements or loops.
Something along the lines of what I did in #133 with categories.
I don't know how one would declare that kind of information in the scheme queries. I'm not really familiar with them, but could that be done using captures? Maybe you have an idea?

**Comment by syphar** [comment]
I'm on my phone, so only a short answer: 

Until there is a general feature, I believe you could achieve this by copying the respective `context.scm` queries into your neovim config, **without adding the typical `;;extends` on the top. 

Then you can remove the queries that you don't want to be used.

**Comment by lewis6991** [comment]
I think this is the way until we can figure out a general mechanism.
