### ISSUE TITLE
Allow setup inside `nvim-treesitter`

### ISSUE THREAD

**Issue by CalebDW** [nvim-treesitter/nvim-treesitter-context#263]
### Description

Hello!

I would be nice to setup up this plugin from inside treesitter similar to several other plugins (autotag, endwise, playground, textobjects, etc):

Example from playground:
![image](https://user-images.githubusercontent.com/4176520/236571399-1dd98bee-86e5-4f3f-bda3-f1caf07b32a6.png)

Thanks!

### Neovim version

0.10

### Actual behavior

See description

### Minimal config

```Lua
See description
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
nvim-treesitter modules are planned to be removed.

**Comment by bew** [comment]
> nvim-treesitter modules are planned to be removed.

Do you have a link to relevant discussion / issue?

**Comment by lewis6991** [comment]
All discussion is on matrix. It's well agreed in the team that nvim-treesitter modules are a big mistake.

**Comment by lewis6991** [comment]
Also see https://github.com/nvim-treesitter/nvim-treesitter/issues/4767
