### ISSUE TITLE
Window stays on top of file tree (nvim-tree)

### ISSUE THREAD

**Issue by schizophrenical** [nvim-treesitter/nvim-treesitter-context#272]
### Description

Thank you for this awesome plugin.

The context appears as expected, however when a file tree (`nvim-tree` as tested) is toggled/opened, the context window does not adjust and ends up on top of `nvim-tree` as well. I don't have enough screenshots but I remember the behavior before is the context window closes/disappear when the window loses focus. I might be wrong though.

I tried adjusting the z-index but it the issue still persist (I think because the file tree is just a split window).

If this is not a bug or just a user-error, feel free to close.

### Neovim version

NVIM v0.9.0

### Expected behavior

The context window recognizes the loss of focus and adjusts accordingly or hides itself.

### Actual behavior

The context window 'overflows' to the file tree.

Below are screenshots using a minimal config.
![Screenshot_2023-05-11-18-27-08_3440x1440](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/117723239/8ed37d0b-c53e-4231-a4cc-c2d884afcd3d)

Without a colorscheme (just a test if the colorscheme is affecting the context window):
![Screenshot_2023-05-11-18-28-46_3440x1440](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/117723239/5b0222f2-d718-4621-810f-65555fbbc91f)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      -- Treesitter
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      'nvim-treesitter/nvim-treesitter-context',
      'nvim-tree/nvim-tree.lua',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')

  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- Treesitter
  require('nvim-treesitter.configs').setup {
    -- A list of parser names, or "all"
    ensure_installed = { 'lua' },
    sync_install = false,
    auto_install = true,
    ignore_install = {},
    highlight = {
      enable = true,
      disable = {},
      additional_vim_regex_highlighting = false,
    },
  }
  -- treesitter-context
  require('treesitter-context').setup()
  -- NvimTree
  require('nvim-tree').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Navigate file until the context window appears.
3. Toggle the file tree.

**Comment by lewis6991** [comment]
This is a really bad `minimal.lua` (why is telescope and packer included?), and the repro instructions aren't clear enough.

> 3. Toggle the file tree.

I didn't know how to do this. You should have put run `:NvimTreeOpen`.

Despite the bad issue report, I've been able to reproduce.
