### ISSUE TITLE
Context is displayed when jumping to netrw 

### ISSUE THREAD

**Issue by Molter73** [nvim-treesitter/nvim-treesitter-context#281]
### Description

When a context is shown and switching to netrw (by running `:Ex`), the context is persisted in the netrw buffer, as if the cursor was still on the previous buffer.

### Neovim version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.0/share/nvim"  Run :checkhealth for more info

### Expected behavior

The context shouldn't be shown in the netrw buffer.

### Actual behavior

Inside a file showing context: 
![Screenshot 2023-05-26 at 10 16 50](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/20206636/d933001e-4bf2-4908-a40e-077a208ffb8e)

Run `:Ex`:
![Screenshot 2023-05-26 at 10 17 07](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/20206636/f380eeeb-dfd0-4c42-a822-8e458ce612d5)

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open a file and place the cursor in a line that shows a context at the top.
3. Run `:Ex`

**Comment by ojroques** [comment]
I have the same issue with [dirbuf](https://github.com/elihunter173/dirbuf.nvim).

**Comment by lewis6991** [comment]
PR welcome
