### ISSUE TITLE
Golang nested test cases are not recognized

### ISSUE THREAD

**Issue by relaxdiego** [nvim-treesitter/nvim-treesitter-context#290]
### Description

Given the following tests:

```
func TestParent(t *testing.T) {
    t.Run("Test Child 1", func(t *testing.T) {
        ...
    }
```

Only `func TestParent(t *testing.T)` is recognized while `t.Run("Test Child 1", func(t *testing.T)` is not.

### Neovim version

v0.9.1

### Expected behavior

The following would be sticky at the top when scrolling:

```
func TestParent(t *testing.T) {
    t.Run("Test Child 1", func(t *testing.T) {
```

### Actual behavior

Only the following is sticky:

```
func TestParent(t *testing.T) {
```

### Minimal config

```Lua
default
```

### Steps to reproduce

Open a golang file such as:

```
package main

import "testing"

func TestParent(t *testing.T) {
    t.Run("Test Child 1", func(t *testing.T) {
        ...
    }
```

Scroll within the `t.Run()` anonymous function argument.

**Comment by lewis6991** [comment]
PR welcome.
