### ISSUE TITLE
Support keeping multiline context even as moving cursor up removes available lines

### ISSUE THREAD

**Issue by scottyantipa** [nvim-treesitter/nvim-treesitter-context#293]
### Description

To reproduce the issue I used the source of this repo, specifically this context: https://github.com/nvim-treesitter/nvim-treesitter-context/blob/6eccc445394df5ab9b1c1e2c445c033949a6a784/lua/treesitter-context.lua#L117

In the screencast below you can see that I'm inside of a multiline context with about 3-4 nested levels in Lua. As I `k` to move up, removing the available space at the top of the buffer, the rendered context by nvim-treesitter-context gets shrunk one line at a time. It would be nice to instead keep the cursor in the same vertical position and just add an extra rendered line
https://github.com/nvim-treesitter/nvim-treesitter-context/assets/3643611/1ca6041b-ed4c-4bf2-a965-65ca657cf409

### Neovim version

NVIM v0.9.1

### Expected behavior

Here's an example of how context.nvim handles it:

https://github.com/nvim-treesitter/nvim-treesitter-context/assets/3643611/4c010708-5fe1-4db4-b760-8b59916adbb5

### Actual behavior

The outer most context gets removed.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open a file that has several nested blocks and scroll such that you have a multi-line context
3. Now try moving up, eg `k`, so that fewer lines are available at the top
4. You'll see the outtermost context disappear. I would expect the inner context lines to disappear first

**Comment by lewis6991** [comment]
Isn't this just:

```lua
require'treesitter-context'.setup{
  trim_scope = 'inner'
}
```
