### ISSUE TITLE
zen-mode compatiblity

### ISSUE THREAD

**Issue by joelpeapen** [nvim-treesitter/nvim-treesitter-context#297]
I'm using [zen mode](https://github.com/folke/zen-mode.nvim) and it's z-index is set to 40. nvim-treesitter-context's z-index is 20 so context doesn't show up in zen mode. Can the zindex of nr be set to a value higher than 40, or will this have side effects?

**Comment by lewis6991** [comment]
Sorry don't use zen mode.
