### ISSUE TITLE
Update to tree-sitter-python introduced bug

### ISSUE THREAD

**Issue by RayJameson** [nvim-treesitter/nvim-treesitter-context#298]
### Description

After [this PR](https://github.com/tree-sitter/tree-sitter-python/pull/226) got merged and [the commit got pinned in treesitter](https://github.com/nvim-treesitter/nvim-treesitter/commit/575f5a4b1fcb60c1ac4f560c46a5171454d674ca#), which introduced the bug

### Neovim version

v0.10.0-dev-661+gef94fb69c-Homebrew

### Expected behavior

No error on file enter

### Actual behavior

Error on entering any python file:

```
ERROR; Unable; to; load; context; query; for python:↲
...-ef94fb6/share/nvim/runtime/lua/vim/treesitter/query.lua:;277;: query: invalid; structure; at; position; 513; for language python
```

<img width="1497" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter-context/assets/67468725/9af60b4b-e42d-48a9-81dc-c5795c0b4403">

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. `:TSInstall python`
3. error

**Comment by lewis6991** [comment]
We don't track issues for out of date queries, but will accept a PR.

**Comment by RayJameson** [comment]
I didn't understand a single word of what you just said.

**Comment by lewis6991** [comment]
Queries are what this plugin uses to define contexts for different languages. As parsers are updated, queries need updating too.

PR means "pull request".

**Comment by RayJameson** [comment]
I believe that should fix it, at least it did on my system

**Comment by lewis6991** [comment]
Many thanks!

**Comment by shauryagoel** [comment]
Is there a mapping of the version/commit for `nvim-treesitter-context` which is compatible with the version/commit of `nvim-treesitter`? I am facing the same issue as above and can't update the `nvim-tressitter` to the latest version as that will break my config.

**Comment by lewis6991** [comment]
Not currently.

This repo is mostly community driven. It should aim to be compatible with the HEAD of nvim-treesitter. If it's not then someone needs to fix it via a PR. Raising issues will likely get ignored.
