### ISSUE TITLE
Help adding context for diff files

### ISSUE THREAD

**Issue by samueloph** [nvim-treesitter/nvim-treesitter-context#302]
The steps at https://github.com/nvim-treesitter/nvim-treesitter-context/blob/master/CONTRIBUTING.md are very helpful but I'm not familiar enough with treesitter and the logic behind how context.scm is processed.

I've tried the following:
diff/context.scm 
```
 ([
   (command)
   (index)
   (new_file)
   (old_file)
   (location)
 ] @context)
```

But it didn't work, I must be missing something very simple but I can't even figure out how to investigate this.

This will make it much easier to review long diffs/patches.

**Comment by lewis6991** [comment]
I'm not sure this is possible with the diff parser since the tree needs to be hierarchical to work in order to find node parents.

**Comment by samueloph** [comment]
Got it.

Is there any way I can tell the context plugin to consider everything between two nodes (eg.: from `command` till the next one) as child?

I've opened a feature request to the diff parser in the meantime:
https://github.com/the-mikedavis/tree-sitter-diff/issues/8

**Comment by lewis6991** [comment]
Theoretically it may be possible, however this plugin is designed with the assumption that contexts are always hierarchical in the parse tree.

**Comment by samueloph** [comment]
@lewis6991 the upstream of the diff parser quickly added hierarchy and I pushed a PR to add support for the diff parser, thank you!
