### ISSUE TITLE
go_to_context doesn't work

### ISSUE THREAD

**Issue by MKrbm** [nvim-treesitter/nvim-treesitter-context#311]
### Description

With current main branch, go_to_context doesn't work. 

It seems that `all_contexts` returns `{}`.

Thank you.

### Neovim version

v0.9.1

### Actual behavior

Nothing happens

### Minimal config

```Lua
I'm using `nvimdots` with default settings.
```

### Steps to reproduce

- Install `nvimdots`
- Invoke `go_to_context`

**Comment by lewis6991** [comment]
> I'm using `nvimdots` with default settings.

Sorry this isn't acceptable

**Comment by MKrbm** [comment]
Sorry, I was misunderstanding the feature of go_to_context(). 
So the function only allow to jump to context only when contexts shows up on the top, right?
Can I jump to its context anytime?

**Comment by lewis6991** [comment]
No

**Comment by MKrbm** [comment]
Will you implement this feature or not planned yet? 
If not, are there any technical reasons for that?

**Comment by lewis6991** [comment]
No
