### ISSUE TITLE
E11: while trying to close windows inside of the command-line window

### ISSUE THREAD

**Issue by TheLeoP** [nvim-treesitter/nvim-treesitter-context#314]
### Description

Somehow #309 is causing me a different error than the one on #306. In my case, Neovim refuses to close windows while inside the command-line window (`E11`).

I don't know the codebase, but my very naive solution was to change the logic [here](https://github.com/nvim-treesitter/nvim-treesitter-context/blob/5dd8c2121170f806c3d0689d9e0dd24250e4f342/lua/treesitter-context.lua#L409) to check if the current window was the command-line window, if no, everything works as normal, if yes, the `winid` gets stored (on the table `ids`) to be deleted later.

```lua
local ids = {}
local function win_close(winid)
  vim.schedule(function()
    if winid ~= nil and api.nvim_win_is_valid(winid) then
      if fn.getcmdwintype() == '' then
        api.nvim_win_close(winid, true)
      else
        table.insert(ids, winid)
      end
    end
  end)
end
```

Then, I created an autocmd at startup that fires when someone exits the command-line window and deletes the windows that weren't previously deleted (whose `id`s are stored in the `ids` table.

```lua
local group = vim.api.nvim_create_augroup('DeleteCmdWin', {})
vim.api.nvim_create_autocmd('CmdwinLeave', {
  group = group,
  callback = function()
    vim.schedule(function()
      for _, id in ipairs(ids) do
        if id ~= nil and vim.api.nvim_win_is_valid(id) then
          vim.api.nvim_win_close(id, true)
        end
      end
      ids = {}
    end)
  end,
})
```

I'm not confident opening a PR because I don't know anything about the codebase.

### Neovim version

NVIM v0.9.1

### Expected behavior

The plugin should handle this error

### Actual behavior

`E11` is shown multiple times and some context windows linger around without being closed.

### Minimal config

```Lua
local plugins = {
	ts = "https://github.com/nvim-treesitter/nvim-treesitter",
	ts_context = "https://github.com/nvim-treesitter/nvim-treesitter-context",
	-- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
	local install_path = "/tmp/nvim/site/" .. name
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.o.runtimepath = install_path .. "," .. vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
require("nvim-treesitter.configs").setup({
	ensure_installed = { "lua" },
	highlight = {
		enabled = true,
	},
})
require("treesitter-context").setup()
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua test.lua` (where `test.lua` has the following code)
```Lua
return {
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
	-- emtpy
}
```
2. `G` to go to the last line
3. `q:` to open the command-line window

**Comment by lewis6991** [comment]
I can't reproduce on latest master.

**Comment by TheLeoP** [comment]
> I can't reproduce on latest master.

By latest master you mean `nvim-treesitter-context` latest master or `Neovim` latest master?

I can reproduce the error on `nvim-treesitter-context` latest master and Neovim version 0.9.1, but it's true that the error does not show up if I use the nightly version of Neovim. Could this be a bug on Neovim itself that got solved on nightly?

**Comment by lewis6991** [comment]
I think I remember a couple patches related to this recently so yeah I think this could be fixed.

**Comment by TheLeoP** [comment]
Thanks for your help, I'll close the issue c:
