### ISSUE TITLE
neovim will crash instead of displaying context window

### ISSUE THREAD

**Issue by gegoune** [nvim-treesitter/nvim-treesitter-context#321]
### Description

After updating both neovim and all my plugins, including nvim-treesitter-context neovim will crash every time when nvim-treesitter-context's context window should be displayed. I have tested it with vue and lua filetypes and both trigger crash.

Example vue file can be obtain from https://vuejs.org/examples/#form-bindings, but from my testing lua file will do as well.

### Neovim version

```
NVIM v0.10.0-dev-959+ga6d0535c1-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Expected behavior

Show context at the top of window without crashing nvim.

### Actual behavior

nvim crashes. It just closes, no information is printed, but that's probably(?) expected since I run Release build.

### Minimal config

```Lua
local plugins = {
  ts = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/' .. name
  if vim.fn.isdirectory(install_path) == 0 then vim.fn.system { 'git', 'clone', '--depth=1', url, install_path } end
  vim.o.runtimepath = install_path .. ',' .. vim.o.runtimepath
end

require('nvim-treesitter.configs').setup {
  auto_install = true,
  ensure_installed = { 'vue' },
}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua any-file-long-enough-to-trigger-context-to-show`
2. move cursor to place which should trigger context window to display

**Comment by lewis6991** [comment]
> nvim crashes. It just closes, no information is printed, but that's probably(?) expected since I run Release build.

This suggests to me your parsers are broken. Are you sure TS context is needed to produce the crash?

Otherwise can you bisect to the commit that introduced the issue?

**Comment by gegoune** [comment]
> > nvim crashes. It just closes, no information is printed, but that's probably(?) expected since I run Release build.
> 
> This suggests to me your parsers are broken. Are you sure TS context is needed to produce the crash?

I haven't got any additional queries installed, is that what you meant?
Yes, TS context is required, without it there is no crash with mine or provided minimal configuration.
 
> Otherwise can you bisect to the commit that introduced the issue?

`4d497f8e5618cc5dd225d028025c76cfd93fb78d is the first bad commit`

It's not the most recent change which makes me think that it's some combination of having updated neovim as well.

**Comment by lewis6991** [comment]
4d497f8e5618cc5dd225d028025c76cfd93fb78d is well over a month old and there's nothing in it that should cause any problems.

Since it's a crash, it's really an issue for Neovim core, and you'll have to get hold of a backtrace (from a debug build) in order for anyone of having any chance of helping.

**Comment by gegoune** [comment]
I have build Debug version now,

```
❯ ~/local/nvim/bin/nvim --version
NVIM v0.10.0-dev-959+ga6d0535c1
Build type: Debug
LuaJIT 2.1.1692716794
```

Can still reproduce issue with minimal config but unfortunately manner in which neovim quits is still the same - there is no backtrace, it just quits with exit code 134. Is there anything I need to do to enable debugging?

**Comment by lewis6991** [comment]
There will be a backtrace, you just need to get to it.

https://github.com/neovim/neovim/wiki/FAQ#debug

**Comment by gegoune** [comment]
There is a backtrace, only saw it in Console, thought it would get printed to terminal emulator.

I appreciate you closed the issue but will post it here in case it is related to this plugin, also not sure why changing to that over month old commit (or removing ts content all together) causes the issue to go away.

Anyways, here is the backtrace, accept my apologies if it isn't TS context's fault after all.

```
Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   nvim [90387]

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1940c8764 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1940ffc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x19400dae8 abort + 180
3   nvim                          	       0x1004de33c u_force_get_undo_header + 256 (undo.c:3220)
4   nvim                          	       0x10028b6a8 u_extmark_copy + 60 (extmark.c:455)
5   nvim                          	       0x10028bca4 extmark_splice_impl + 312 (extmark.c:625)
6   nvim                          	       0x10028c73c extmark_splice + 216 (extmark.c:603)
7   nvim                          	       0x100108a5c nvim_buf_set_lines + 1812 (buffer.c:470)
8   nvim                          	       0x1000ecb30 nlua_api_nvim_buf_set_lines + 560 (lua_api_c_bindings.generated.c:575)
9   nvim                          	       0x1005b6994 lj_BC_FUNCC + 44
10  nvim                          	       0x1005ccb58 lua_pcall + 228 (lj_api.c:1145)
11  nvim                          	       0x1002ebec4 nlua_call_ref + 268 (executor.c:1591)
12  nvim                          	       0x100165608 call_autocmd_callback + 2116 (autocmd.c:2007)
13  nvim                          	       0x100164c34 getnextac + 596 (autocmd.c:2064)
14  nvim                          	       0x10025b644 do_cmdline + 2152 (ex_docmd.c:505)
15  nvim                          	       0x100162f4c apply_autocmds_group + 2712 (autocmd.c:1792)
16  nvim                          	       0x100164268 apply_autocmds + 80 (autocmd.c:1462)
17  nvim                          	       0x100373fe4 normal_check_cursor_moved + 372 (normal.c:1289)
18  nvim                          	       0x100373a98 normal_check + 252 (normal.c:1428)
19  nvim                          	       0x10047e0c8 state_enter + 84 (state.c:40)
20  nvim                          	       0x1003625a0 normal_enter + 208 (normal.c:517)
21  nvim                          	       0x1000e324c main + 4720 (main.c:647)
22  dyld                          	       0x193da7f28 start + 2236
```

> Try and compile the parsers with -Werror=implicit-function-declaration if you can.

I am not quite sure how to do that, but can try with some help.

**Comment by gegoune** [comment]
On top of that I have bisected neovim, it seems like breaking change was:

```
008154954791001efcc46c28146e21403f3a698b is the first bad commit
commit 008154954791001efcc46c28146e21403f3a698b
Author: bfredl <bjorn.linse@gmail.com>
Date:   Mon Aug 21 14:52:17 2023 +0200

    refactor(change): do API changes to buffer without curbuf switch

    Most of the messy things when changing a non-current buffer is
    not about the buffer, it is about windows. In particular, it is about
    `curwin`.

    When editing a non-current buffer which is displayed in some other
    window in the current tabpage, one such window will be "borrowed" as the
    curwin. But this means if two or more non-current windows displayed the buffers,
    one of them will be treated differenty. this is not desirable.

    In particular, with nvim_buf_set_text, cursor _column_ position was only
    corrected for one single window. Two new tests are added: the test
    with just one non-current window passes, but the one with two didn't.

    Two corresponding such tests were also added for nvim_buf_set_lines.
    This already worked correctly on master, but make sure this is
    well-tested for future refactors.

    Also, nvim_create_buf no longer invokes autocmds just because you happened
    to use `scratch=true`. No option value was changed, therefore OptionSet
    must not be fired.
```

so perhaps TS context will need to adapt somehow? Doesn't it rule out parsers' issues?

**Comment by lewis6991** [comment]
That change is known to be causing issues. It is best to raise a neovim core issue.

**Comment by lewis6991** [comment]
And

**Comment by bfredl** [comment]
Crash hopefully fixed with just merged https://github.com/neovim/neovim/pull/24889 . Let me know if there still are issues.

**Comment by gegoune** [comment]
Crash fixed indeed, thank you both very much!
