### ISSUE TITLE
`config.enable = false` no longer works after `e6b743ccd4e780bc9cd85b707de67df72eea1a23`

### ISSUE THREAD

**Issue by levouh** [nvim-treesitter/nvim-treesitter-context#324]
### Description

Passing `enable = false` to the table passed to `setup(...)` no longer works after e6b743ccd4e780bc9cd85b707de67df72eea1a23. All works fine as-of 00fb2f7078ab4a5196d57a6c1c344c9e8489a68e.

### Neovim version

N/A

### Expected behaviour

Context should not appear on startup if user configuration contains `enable = false`

### Actual behaviour

Context appears, regardless of configuration having `enable = false`

### Minimal config

```Lua
-- Shouldn't matter, will add if needed.
```

### Steps to reproduce

Shouldn't matter, will add if needed.

Pass `enable = false` to configuration and observe the plugin is still enabled.

**Comment by levouh** [comment]
Haven't done anything beyond a bisect @lewis6991, will look at the commits as time permits to see if the issue is somewhat obvious or not.

**Comment by levouh** [comment]
Quick glance, I believe it is because `plugin/treesitter-context.lua` is loaded automatically per `rtp` stuff, so when `setup()` gets called with no arguments, it defaults to `enabled = true`.

**Comment by levouh** [comment]
Previously there was:

```lua
autocmd_for_group('treesitter_context')('VimEnter', function()
  M.setup()
end)
```

so if the plugin was lazy-loaded, this wouldn't do anything (as far as I can tell it doesn't check `vim.v.vim_did_enter` later as well). However with the newest changes (and due to the idempotent nature of checking the module-local `did_setup`), the user actually now _cannot_ specify configuration beyond the defaults it seems.

**Comment by lewis6991** [comment]
To fix this we just need to move the `did_setup` check lower down.

Btw, I wouldn't recommend lazy loading this plugin. There really is no need.

**Comment by levouh** [comment]
>Btw, I wouldn't recommend lazy loading this plugin. There really is no need.

But how else will I get my startup time _blazing fast_???

`\s`

>They can if they call setup in their init.lua.

After moving/changing `did_setup`, right?

**Comment by lewis6991** [comment]
Ah `lazy.nvim` calls `plugin/` _during_ ` init.lua` (incorrectly IMO), so this `setup()` won't work with that plugin manager.
