### ISSUE TITLE
Error executing 'nvim_win_close' when opeining command window

### ISSUE THREAD

**Issue by bravo1003** [nvim-treesitter/nvim-treesitter-context#327]
### Description

Upon entering command window with "q:", the following message appear and conext is stucked after command window is closed.

```
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:303: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_win_close'
	...vim-treesitter-context/lua/treesitter-context/render.lua:303: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:301>
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:303: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_win_close'
	...vim-treesitter-context/lua/treesitter-context/render.lua:303: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:301>
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:303: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_win_close'
	...vim-treesitter-context/lua/treesitter-context/render.lua:303: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:301>
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:303: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_win_close'
	...vim-treesitter-context/lua/treesitter-context/render.lua:303: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:301>

```

### Neovim version

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Expected behavior

No error and treesitter context display correctly

### Actual behavior

Errors and treesitter context stuck displaying in the window.

https://github.com/nvim-treesitter/nvim-treesitter-context/assets/5191595/9e3836db-c700-491b-b0f0-c0702d8d9831

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end
```

### Steps to reproduce

1. Make sure context is displaying
2. Enter command window with `:qa`

**Comment by lewis6991** [comment]
This is an issue with v0.9 and is already fixed on neovim nightly.

**Comment by bravo1003** [comment]
Thank you for the answer. Indeed it is fixed nightly version

**Comment by bew** [comment]
Hello, is there a way to silence this error while waiting for the next neovim release?

**Comment by bravo1003** [comment]
@bew 
You can setup  routes to filter out nvim_win_close error message.
This is how I do it.

```lua
routes = {
    {
      filter = { event = "msg_show", find = "nvim_win_close" },
      opts = { skip = true },
    },
}
```

**Comment by lewis6991** [comment]
Does #330 fix this?

**Comment by mhdna** [comment]
> Does #330 fix this?

Nope.

**Comment by bravo1003** [comment]
@lewis6991 ,

> Does https://github.com/nvim-treesitter/nvim-treesitter-context/pull/330 fix this?

The rendering part in cmdline window  is fixed.
nvim_win_close error will still popup but I think that's issue with neovim.

**Comment by sainttttt** [comment]
> ```lua
> routes = {
>     {
>       filter = { event = "msg_show", find = "nvim_win_close" },
>       opts = { skip = true },
>     },
> }
> ```

This worked for me thanks. Just FYI for anyone else reading, I used this for noice.nvim

**Comment by yads** [comment]
> You can setup routes to filter out nvim_win_close error message. This is how I do it.
> 
> ```lua
> routes = {
>     {
>       filter = { event = "msg_show", find = "nvim_win_close" },
>       opts = { skip = true },
>     },
> }
> ```

Where would this configuration setting go?

**Comment by sainttttt** [comment]
> > You can setup routes to filter out nvim_win_close error message. This is how I do it.
> > ```lua
> > routes = {
> >     {
> >       filter = { event = "msg_show", find = "nvim_win_close" },
> >       opts = { skip = true },
> >     },
> > }
> > ```
> 
> Where would this configuration setting go?

This goes in the config of [noice.nvim](https://github.com/folke/noice.nvim) - it can be used to filter out error messages

**Comment by yads** [comment]
Ah ok, so it has to be used with noice.nvim. Ok I guess I'll wait for a neovim release that fixes this. Thanks.
