### ISSUE TITLE
Function signatures are displayed in multiple lines

### ISSUE THREAD

**Issue by dhananjaylatkar** [nvim-treesitter/nvim-treesitter-context#332]
### Description

Earlier when function signature was multiple line, context used to combine all of lines into single line. Now it shows same in multiple lines. It seems waste of space to show same amount of info using more lines.

e.g.
Func definition
```c
static void do_something_interesting(int a,
                                     int b,
                                     char *c)
{
    // interesting stuff
}
```

Earlier behavior when `do_something_interesting` was in context
```c
static void do_something_interesting(int a, int b, char *c) {


// code far below
```

After update it takes 4 lines to show the func definition context.

Is there a config option for prev behavior?

### Neovim version

NVIM v0.9.1

### Expected behavior

Explained above

### Actual behavior

Explained above

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
Yes, this is intentional. Collapsing multiple lines was too complicated and lead to many issues.

If you want to limit the amount of lines each context can populate then use `config.multiline_threshold`

**Comment by dhananjaylatkar** [comment]
`config.multiline_threshold=1` can hide function name if return type is defined on separate line. I'm trying `config.multiline_threshold=2` for now. Let's see if I get used to this.

Can you tell me which commit made this change?

**Comment by stagnation** [comment]
Thanks! Some of my python plotting function signatures have reached astronomical heights with all the typehints.
Is there a way to change this with a key-bind? To pop the full signature up? Or, if you know another alternative to peek at the function defintion/context I'm in.

**Comment by lewis6991** [comment]
Not currently but that seems like a worthwhile thing to support.

**Comment by dhananjaylatkar** [comment]
19a265d7f73d20cf3e466a65094a82ea90988986 -> collapse feature removed
e5676455c7e68069c6299facd4b5c4eb80cc4e9d -> pin to this if you want collapse feature and don't care about updates
