### ISSUE TITLE
set wrap option  show multiple line from same context

### ISSUE THREAD

**Issue by grimgort** [nvim-treesitter/nvim-treesitter-context#334]
### Description

wrap option is no compatible with this plugin. 
When a new context appears, it is hidden by the "wrap" line of the function

### Neovim version

0.9.2

### Expected behavior

![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/44238325/7cb418b3-a88d-4c56-a198-f43d280bd056)

### Actual behavior

![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/44238325/2112e6de-a03a-4b69-a92f-4cea59d2c2a2)

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then


    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
No repro, insta-close
