### ISSUE TITLE
Why nvim-treesitter-context doesn't use nvim-treesitter.configs like nvim-treesitter-textobjects

### ISSUE THREAD

**Issue by Freed-Wu** [nvim-treesitter/nvim-treesitter-context#340]
Currently, nvim-treesitter-context can be configure by:

```lua
require "treesitter-context".setup {}
```

Why not

```lua

require "nvim-treesitter.configs".setup {
  context = {
    ...
  }
}
```

to keep consistent with other nvim-treesitter extensions?

**Comment by bew** [comment]
Note that the module extension system in nvim-treesitter is going to be removed.
See: https://github.com/nvim-treesitter/nvim-treesitter/issues/4767

**Comment by Freed-Wu** [comment]
Oh, I see. Thanks!

**Comment by lewis6991** [comment]
Also this plugin does not require nvim-treesitter
