### ISSUE TITLE
Improve queries for Clojure, Janet, and Fennel.

### ISSUE THREAD

**Issue by harryvederci** [nvim-treesitter/nvim-treesitter-context#345]
The current Clojure, Janet, and Fennel queries are already very useful.

One thing that can be improved is how the context of tables/dictionaries/etc is displayed.

Currently, the line containing the start of a hash-map is displayed in the context:
```
{:key-1 "value-1"
```

If the value is on the next line, the context shows:
```
{:key-1
```

When scrolling down this can be confusing if keys and values are not on the same lines. In the following example, the context will show `{:key-1` even when you've scrolled down to `"value-2"`. 
```
{:key-1
 "value-1"
 :key-2
 "value-2"}
```

I think this may be possible with `context.end`, but I haven't been able to fix it myself.

**Comment by lewis6991** [comment]
We don't track issues for specific languages.
