### ISSUE TITLE
Error when using unicode separator

### ISSUE THREAD

**Issue by paul-hansen** [nvim-treesitter/nvim-treesitter-context#350]
### Description

I attempted to use [〜](https://www.compart.com/en/unicode/U+301C) or [〰](https://www.compart.com/en/unicode/U+3030) as the separator and I received an error.

Not a big, deal feel free to close if you don't want to address it. I'm not even sure those characters will look good. Just thought I'd report in case it was an easy fix or someone wanted to make the error handling better so you aren't almost locked out of nvim if you make this mistake.

Thanks for making this plugin it's been very helpful!

### Neovim version

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1696795921

### Expected behavior

Expected to be able to use unicode characters as separators

### Actual behavior

When a unicode character is set as the separator this error is spammed every time I do an action preventing use of nvim. To revert it I had to restart nvim, revert the separator and run :PackerSync before treesitter initialized.
```
E5108: Error executing lua WinEnter Autocommands for "*": Vim(append):Error executing lua callback: ...vim-treesitter-context/l
ua/treesitter-context/render.lua:51: border chars must be one cell
stack traceback:
        [C]: in function 'nvim_open_win'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:51: in function 'display_window'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:337: in function 'open'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:50: in function 'open'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:111: in function 'f'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:27: in function <...start/nvim-treesitter-context/lua/trees
itter-context.lua:21>
        [C]: in function 'execute'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:998: in function 'quit'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'execute'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:998: in function 'quit'
        [string ":lua"]:1: in main chunk
```

### Minimal config

```Lua
use {
	"nvim-treesitter/nvim-treesitter-context",
	config = function()
		require'treesitter-context'.setup{
			mode = 'topline',
			separator = '〰',
		}
	end
}
```

### Steps to reproduce

1. Change this plugin's separator option to `〰`
2. PackerSync (or equivalent)
3. Try to scroll a buffer that has treesitter enabled.
4. Observe error

**Comment by lewis6991** [comment]
This is a problem with `nvim_open_win`

**Comment by paul-hansen** [comment]
Ah yeah I can replicate the error using this:
```
:lua vim.api.nvim_open_win(0, false, {border={"╔", "═" ,"╗", "║", "╝", "═", "╚", "〰"}, width=12, height=3, relative='win', row=3,col=3})
```
Thanks! I'll see if there's a related issue for neovim or open on there.

**Comment by paul-hansen** [comment]
Actually now that I look at it again, those characters are actually displayed as two cells in nvim so it makes sense it wouldn't be able to use them for borders since it wouldn't work for odd numbered widths. 
![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/7019130/2458df14-4d83-4a39-9e59-7d424078e185)

So it makes sense that this probably isn't fixable. Sorry for the bother, seems pretty obvious now.
