### ISSUE TITLE
multi line context nodes

### ISSUE THREAD

**Issue by Saecki** [nvim-treesitter/nvim-treesitter-context#352]
I see that #316 changed the way multiline contexts are displayed.

I kind of liked the way lines were concatenated before, but I definitely see the appeal from a maintainer's perspective. So if someone would be willing to introduce a configuration option that would make things work like before, that would be awesome.

Also maybe an option to limit the number of contexts, in addition to the number of lines (`max_lines`) would be nice.

**Comment by kiyoon** [comment]
I would also like to have it in a single line. In Python the formatter always makes it into a multiple line, but personally I find it much more concise with 1 line as the context.

**Comment by lewis6991** [comment]
Sorry not happening.
