### ISSUE TITLE
Transparency for TSContext

### ISSUE THREAD

**Issue by bomcon123456** [nvim-treesitter/nvim-treesitter-context#355]
Awesome plugins, I'm loving it so far!!
But I was wondering how I can make the Context background Ítransparent, I've tried to set the TreesitterContext `bg="none"` but it just changes to be pure black.
Any help would be nice, thanks!
![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/20278911/e15b6d25-7c70-4c3b-9145-bb9d734d03f7)

**Comment by Danielkonge** [comment]
`:hi TreesitterContext guibg=none` works for me.

**Comment by b11e** [comment]
This is what I have in my config

```  {
    "nvim-treesitter/nvim-treesitter-context",
    enabled = true,
    opts = function()
      -- make transparent
      vim.api.nvim_set_hl(0, "TreesitterContext", { bg = "none" })
      return {
        -- your other treesitter-context options here
      }
    end,
  },
```
