### ISSUE TITLE
Don't include comments in the context window

### ISSUE THREAD

**Issue by nogweii** [nvim-treesitter/nvim-treesitter-context#361]
### Description

At least in Ruby, I like to have larger, multi-line explanatory comments. That's great and all, but when I scroll down, the entire block is stuck with the class/function and fills up a lot of the screen.

<details><summary>sample.rb</summary>
<p>

```ruby
class Sample
  # Lorem ipsum suscipit velit reiciendis ex aliquid sed. Et qui amet aspernatur
  # voluptatem iusto atque quo. Cumque itaque aut pariatur adipisci est eius et.
  # Ratione laborum eos mollitia tenetur laboriosam sed. Blanditiis excepturi
  # dolores magni et qui non aut doloremque. Et sequi distinctio ut et alias.
  # i don't know what this code is, I just started typing things
  def do_a_thing(a, b)
    a.join(' ').split(/./).each do |char|
      case char
      when 'a'..'z'
        b.upcase
      when 'A'..'Z'
        b.upcase
      when '0'..'9'
        -1 * b.to_i
      else
        b + b
      end
    end
  end
end
```

</p>
</details> 

### Neovim version

v0.9.4 on Arch Linux

### Expected behavior

Only the `class` and `def` lines are shown, and the comment hidden from the context popup.

### Actual behavior

The comment is included, in full, and obscures a large part of the editor's screen.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end
```

### Steps to reproduce

1. Have a terminal that's shorter than usual, like only 15 or 20 lines tall.
2. `nvim --clean -u minimal.lua sample.rb`
3. Scroll down some

**Comment by bew** [comment]
Why close? I think it's a very valid request 🤔

**Comment by lewis6991** [comment]
Because I don't want to and I'm currently the only maintainer.

Features aren't free.

**Comment by nogweii** [comment]
Ah, sorry, this came across a little more demand-y / blunt than I intended, sorry.

I'd be glad to work on it, but I'm not entirely sure where to start on this. I don't see anything that intentionally grabs the comments in the queries, so do those need to be tweaked to exclude them?

**Comment by lewis6991** [comment]
No problem.

I'm pretty sure this is a specific problem with the context queries for the language you are using as comments aren't treated any specially and the queries specify exactly what the context is.

**Comment by ghostfish0** [comment]
@nogweii Hi I'm facing similar issues, any news on this front? Did you resolve this? Many thanks :)

**Comment by CodeVogel** [comment]
@lewis6991 
I wanted to ask for some clarification on this - It's totally fair that you don't want to spend time on this yourself, but would you be accepting PR's that offer this behaviour as a config option? Or would you rather not see these come in due to future maintenance?

Thanks :)

**Comment by lewis6991** [comment]
You need to make sure the queries do not include comments.

**Comment by lewis6991** [comment]
Needs to be handled in the queries,  not the Lua implementation.
