### ISSUE TITLE
Plugin causes nvim to exit with exit status 1.

### ISSUE THREAD

**Issue by FalcoGer** [nvim-treesitter/nvim-treesitter-context#367]
### Description

Loading this plugin causes nvim to exit with exit code 1 when quitting. While normally not a problem, this creates issues when using nvim as the editor for git commits, since git commit fails when the editor exits with any code other than 0.

### Neovim version

v0.10.0-dev-e59cf3b3a

### Expected behavior

nvim exits with code 0 (success)

### Actual behavior

nvim exits with code 1 (failure)

### Minimal config

```Lua
set nocompatible

filetype off
call plug#begin(expand('~/.vim/plugged'))
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} | let g:user_loaded_treesitter = 1

if exists('g:user_loaded_treesitter')
    Plug 'nvim-treesitter/nvim-treesitter-context' | let g:user_loaded_treesitter_context = 1
endif
call plug#end()
filetype plugin indent on

if has("syntax")
  syntax on
endif

set guioptions+=a

set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set hidden
set mouse=a

lua << EOF
local ts_config = require 'nvim-treesitter.configs'
local options = {}
ts_config.setup(options)

local tsc = require('treesitter-context')
local options = {
    enable = true,
}

tsc.setup(options)

EOF
```

### Steps to reproduce

1. `nvim -u minimal.lua`
2. `:q`
3. echo $?
4. ???
5. No profit

**Comment by FalcoGer** [comment]
Updated to [latest nightly](https://github.com/neovim/neovim/commit/cdc8bacc7945da816738e330555fa85d3ffffd56), issue still present.

This pops up in the log file at `~/.local/state/nvim/log`
```text
ERR 2023-11-19T04:11:13.676 nvim.552753.0 loop_close:174: uv_loop_close() hang?
[--I] signal   0x564a2152efc8
[-AI] async    0x564a2152ee10
[R--] timer    0x564a234b0700
```

**Comment by FalcoGer** [comment]
Downgraded to stable (0.9.4), still present.

**Comment by lewis6991** [comment]
Sorry I can't help with this. You'll need to debug this yourself as it is probably related to how you build nvim.

We have CI which does similar to your repro steps so the issue probably isn't related to the plugin.

**Comment by FalcoGer** [comment]
What do you mean how I build nvim. There isn't anything special about it. I pull, delete .deps, make deps, goto build, ninja clean, cmake .., and ninja build. Nothing fancy or strange about it.
I don't even know how I would start debugging your code and find out what is causing the exit status. Furthermore I use dozens of plugins, but yours is the one that is causing the issue.

**Comment by lewis6991** [comment]
> but yours is the one that is causing the issue.

For you and you alone.

**Comment by FalcoGer** [comment]
Turns out it's the "IWYU" option with cmake. when that is enabled, your plugin (and yours alone) causes nvim to exit with the failure code.
