### ISSUE TITLE
Enhancement: Add a feature to filter line that is shown.

### ISSUE THREAD

**Issue by kevyuu** [nvim-treesitter/nvim-treesitter-context#368]
```
  void RenderGraphExecution::run()
  {
    SOUL_ASSERT_MAIN_THREAD();
    SOUL_PROFILE_ZONE();
```
For code, with this style of formatting where the bracket is in newline, there will be a lot of wasted line shown with only one open bracket in it. Is there a way to filter out which line to show? I want to be able to filter out this single open bracket line.

**Comment by lewis6991** [comment]
No sorry, you'll need to construct your own queries that work well with your code style.
