### ISSUE TITLE
not working for R code

### ISSUE THREAD

**Issue by rdataforge** [nvim-treesitter/nvim-treesitter-context#381]
### Description

Installed Lazyvim, no customization, just plain out-of-the-box install and nvim-treesitter-context installed via :Lazy
Opened long R file and Toggled TSContext active via keybinds ( leadert + u + t)

Treesitter context is not keeping the function header visible when scrolling down

### Neovim version

NVIM v0.9.2 Build type: RelWithDebInfo LuaJIT 2.1.1694082368

### Expected behavior

the function header is visible when scrolling

### Actual behavior

there is no context as the header is past up the buffer when scrolling reaches bottom

### Minimal config

```Lua
no custom settings, just plain fresh Lazyvim with TSContext installed via Lazy
```

### Steps to reproduce

1. install Lazyvim
2. .install nvim-treesitter-context using :Lazy interface
3. open a long R file
4. activate TSContext with keybindings: leader + u + t
5. scroll down file

**Comment by lewis6991** [comment]
We don't track issues for languages. PR welcome.
