### ISSUE TITLE
Add `'TreesitterContextBottomLineNr'` highlight group

### ISSUE THREAD

**Issue by Danielkonge** [nvim-treesitter/nvim-treesitter-context#383]
Currently my highlighting setup for `treesitter-context` is given by:
```lua
vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = 'None' })
local line_nr = vim.api.nvim_get_hl(0, { name = 'LineNr' })
line_nr.underline = true
line_nr.sp = line_nr.fg
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', line_nr)
```
but I would like to be able to just have the underline under the last line number in the context window. I don't think this is easily achievable with the current code, so I would like to request something like a `'TreesitterContextBottomLineNr'` highlight group.

If you are open to adding that, I can potentially implement it myself.

**Comment by lewis6991** [comment]
There is already `TreesitterContextBottom`. Are you saying you want *another* highlight just for the bottom line number?

**Comment by Danielkonge** [comment]
Yes, if that would be fine with you, I would like another highlight group just for the bottom line number.

My use case is basically the same as for `TreesitterContextBottom`, i.e., create some visual separation between the context and the rest of my text, but I think that `TreesitterContextBottom` does too much when it e.g. underlines across my whole screen. Instead I would like to be able to just put an underline under the last line number in the context, to signal some separation through this much smaller underline.
