### ISSUE TITLE
Context not working for python

### ISSUE THREAD

**Issue by Inovvia** [nvim-treesitter/nvim-treesitter-context#386]
### Description

I tried opening a python filed

### Neovim version

NVIM v0.9.5

### Expected behavior

Context sticking at the top works

### Actual behavior

Error detected while processing CursorMoved Autocommands for "*":
Unable to load context query for python:
...s/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 513 for language python

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
-- Im using lunarvim and installed pyright lsp
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open any python file example - https://raw.githubusercontent.com/seleniumbase/SeleniumBase/master/examples/coffee_cart_tests.py

**Comment by lewis6991** [comment]
It does work. Your setup isn't up-to-date.

**Comment by Inovvia** [comment]
Thanks you were right. Looks like treesitter from Lunarvim is indeed outdated. I just manually updated it. Sorry for wasting your time.
