### ISSUE TITLE
Incompatible with vim-which-key

### ISSUE THREAD

**Issue by SandWoodJones** [nvim-treesitter/nvim-treesitter-context#40]
Bug happens when using this plugin along with [vim-which-key](https://github.com/liuchengxu/vim-which-key) and with `vim.g.which_key_use_floating_win = 1`.
![2021-04-03 01-41-54](https://user-images.githubusercontent.com/35671374/113468671-fdec0d00-941d-11eb-86cc-8c5be0743e29.gif)
After invoking which-key inside a context that is being displayed and exiting it, my screen seems to be vertically split with only one line at the top being active. In this line I can move up and down but not left and right and can't edit text. If I invoke which-key again this error is displayed: 
`Error detected while processing function which_key#start[49]..which_key#window#show[9]..<SNR>53_show_old_win[2]..<SNR>53_open_split_win[2]..<SNR>53_split_or_new:`

**Comment by romgrk** [comment]
The plugin isn't touching any window except its own floating window. @liuchengxu, do you know if this is something that could be caused by vim-which-key?

**Comment by liuchengxu** [comment]
Have no idea. The strange thing is when `g:which_key_use_floating_win` is 1, `s:show_old_win` should not be called, https://github.com/liuchengxu/vim-which-key/blob/794e18deb5e58d261047a774b7d5c0c78d81e9ef/autoload/which_key/window.vim#L161-L164 . What is the value of `g:which_key_use_floating_win`? @SandWoodJones

**Comment by SandWoodJones** [comment]
I've tested with `g:which_key_use_floating_win=0` and there is no problem since which-key uses its own popup window, but I currently use `g:which_key_use_floating_win=1`.

**Comment by liuchengxu** [comment]
What I mean is `s:show_old_win()` should not be invoked when `g:which_key_use_floating_win` is 1, so the error message does not make sense to me. I can take a look if you provide a minimal vimrc, I don't use tree-sitter, so please make the minimal vimrc really simple to reproduce.

**Comment by SandWoodJones** [comment]
minimal rc:
```lua
require('nvim-treesitter.configs').setup {
        highlight = {
                enable = true
        }
}

vim.wo.number = true
vim.g.mapleader = ' '   -- Map leader to spacebar
vim.api.nvim_set_keymap('n', '<leader>', ':<c-u>WhichKey "<Space>"<CR>', {noremap = true, silent = true})
vim.g.which_key_use_floating_win = 0
```
steps to reproduce:
1. Enter a treesitter context (A function for instance)
2. Have `nvim-treesitter-context` display the current context
2. Invoke `which-key`
3. exit `which-key`

**Comment by liuchengxu** [comment]
Don't know how to set this up as I don't use Lua config either :).

**Comment by SandWoodJones** [comment]
Well in neovim it would be the same as loading any regular init.vim, but here is the vimscript version
```vim
lua << EOF
    require'nvim-treesitter.configs'.setup {
        highlight = {
            enable = true
         }
    }
EOF

set number
let g:mapleader=' '
nnoremap <silent> <Leader> :<c-u>WhichKey "<Space>"<CR>
let g:which_key_use_floating_win=0
```

**Comment by liuchengxu** [comment]
I'm using this minimal vimrc:

```vim
call plug#begin('~/.vim/plugged')
Plug 'romgrk/nvim-treesitter-context'
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'liuchengxu/vim-which-key'
call plug#end()

lua << EOF
    require'nvim-treesitter.configs'.setup {
        highlight = {
            enable = true
         }
    }
EOF

set number
let g:mapleader=' '
nnoremap <silent> <Leader> :<c-u>WhichKey "<Space>"<CR>
let g:which_key_use_floating_win=0
```

But runs into this error and I'm too lazy to resolve it.

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...496b9/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/xuliucheng/.vim/plugged/nvim-
treesitter/parser/rust.so: supported between 9 and 12, found 13
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...496b9/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /Users/xuliucheng/.vim/plugged/nvim-
treesitter/parser/rust.so: supported between 9 and 12, found 13
```

**Comment by SandWoodJones** [comment]
Did you install the rust parser with `:TSInstall rust`? If so then maybe [this](https://github.com/nvim-treesitter/nvim-treesitter/issues/994#issuecomment-805213716) solves it?

**Comment by romgrk** [comment]
Compiling the grammar from source can fix the tree-sitter ABI change problem: `:TSInstallFromGrammar rust`.

**Comment by lewis6991** [comment]
This issue is very stale and with little indication that this is an issue with this plugin. Closing.
