### ISSUE TITLE
Context header disappears with markdown_inline parser installed

### ISSUE THREAD

**Issue by polirritmico** [nvim-treesitter/nvim-treesitter-context#400]
### Description

Hi.

When `markdown` and `markdown_inline` parsers are installed, the context header disappears when the cursor is currently on a text line.
`:TSUninstall markdown_inline`  fix the problem.

Bisecting the repo points to this commit 0a95d477c825ac9c787346f97d68cc9f16715f03

Regards

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.0-beta3 Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5/src -I/usr/include-I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

### Expected behavior

The context header should not be disappearing

### Actual behavior

video showing the actual behavior:

https://github.com/nvim-treesitter/nvim-treesitter-context/assets/24460484/38f36b2f-1647-4f89-8502-f1ff315c5fea

### Minimal config

```Lua
local plugins = {
    ts = "https://github.com/nvim-treesitter/nvim-treesitter",
    ts_context = "https://github.com/nvim-treesitter/nvim-treesitter-context",
}

for name, url in pairs(plugins) do
    local install_path = "/tmp/nvim/site/" .. name
    if vim.fn.isdirectory(install_path) == 0 then
        vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
    end
    vim.o.runtimepath = install_path .. "," .. vim.o.runtimepath
end

require("nvim-treesitter.configs").setup({
    auto_install = true,
    ensure_installed = {
        "markdown",
        "markdown_inline",
    },
})
require("treesitter-context").setup({})
```

### Steps to reproduce

1. Test file. `foo.md`:

```markdown
# Title

zt here


Cursor at this line causes the context header to disappear if markdown inline is installed


```

2. `nvim --clean -u minimal.lua foo.md`
3. `zt` on line `2`
4. Move the cursor with `j` to reach line `6`.
5. The context title should disappear.
6. `:TSUninstall markdown_inline` should fix the issue.

**Comment by lewis6991** [comment]
@kwaszczuk
