### ISSUE TITLE
Use one floating window instead of two.

### ISSUE THREAD

**Issue by xzbdmw** [nvim-treesitter/nvim-treesitter-context#415]
### Description

As I described in https://github.com/neovide/neovide/issues/2375#issuecomment-1969194912 
It is embarrassing to see two shadow floating windows in mutigrid

### Neovim version

0.10

### Expected behavior

one glass contain line number

### Actual behavior

two glass

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
No

**Comment by xzbdmw** [comment]
In case someone have the same request, here is a fork version using one window
https://github.com/xzbdmw/nvim-treesitter-context

**Comment by romgrk** [comment]
@lewis6991 Can you add more context? Is there any issue you foresee?

If someone has an implementation with 1 window I'd be happy to accept a PR.

**Comment by lewis6991** [comment]
We can accept a good PR if it doesn't add **any** complexity. The user issue is just that Neovide adds a shadow which I don't think is an issue enough for adding complexity.

I looked at the fork and all it does it prepend the line numbers to each line in the context window (with lots of unnecessary formatting changes), which is a broken way of doing this since it breaks highlighting. So we won't accept that as a PR.

We would need to use either inlay-extmarks, or try and pack the information into the signcolumn (somehow?). Both of those will introduce unnecessary complexity, so I'm not interested in exploring those.

>  I'd be happy to accept a PR.

Do you plan on maintaining it? I'm happy to see you back contributing to the project, but with respect, you seem to have a tendency to take long hiatuses.

**Comment by romgrk** [comment]
Fair points, the tradeoff with complexity is also something that I'm wary of when receiving a PR.

Wdyt about using inlay hints for line numbers? Same window, same buffer, and afaict it wouldn't affect highlights.

**Comment by romgrk** [comment]
Fairs point, I'm also wary of complexity when received a PR.

Why do you think inlay extmarks would introduce too much complexity? Doesn't sound like that much work. I don't have enough bandwidth to implement that but if someone is interested in doing that exploration, do you foresee any issue there?

**Comment by lewis6991** [comment]
> Why do you think inlay extmarks would introduce too much complexity?

Inlay hints are a 0.10 feature so we would instantly drop support for 0.9, and it's likely (as with all new extmark features) that there's still probably some unknown issues with them. Using a second floating window is just closer to what we're trying to emulate, so we don't need to worry about any weird edge cases like alignment and such.

Arguably, Neovide should just be able to render this properly despite there being two windows, provided they have the same z-index.

Lots of plugins use floating windows for all sorts of stuff (e.g. https://github.com/dstein64/nvim-scrollview and https://github.com/lewis6991/satellite.nvim), so the shadow they are rendering is going to generally cause issues.

So really, I'm not convinced this is something we need to address.

**Comment by romgrk** [comment]
> Arguably, Neovide should just be able to render this properly despite there being two windows, provided they have the same z-index.

Valid argument. With that in mind I'm ok with treating this as a neovide issue rather than a bug here. Thanks for the comments.

**Comment by xzbdmw** [comment]
> We can accept a good PR if it doesn't add **any** complexity. The user issue is just that Neovide adds a shadow which I don't think is an issue enough for adding complexity.
> 
> I looked at the fork and all it does it prepend the line numbers to each line in the context window (with lots of unnecessary formatting changes), which is a broken way of doing this since it breaks highlighting. So we won't accept that as a PR.
> 
> We would need to use either inlay-extmarks, or try and pack the information into the signcolumn (somehow?). Both of those will introduce unnecessary complexity, so I'm not interested in exploring those.
> 
> > I'd be happy to accept a PR.
> 
> Do you plan on maintaining it? I'm happy to see you back contributing to the project, but with respect, you seem to have a tendency to take long hiatuses.

Oh I see the broken highlight, and simply add gutterwidth to query's start col and end col fix that, I'm not familiar with highlight stuff so linenumber highlight simply using context window's one.
