### ISSUE TITLE
Multi-line function definition is not handled

### ISSUE THREAD

**Issue by theniceboy** [nvim-treesitter/nvim-treesitter-context#416]
### Description

Given such Dart code below:
```dart
void main({
  required bool a,
  required bool b,
  required bool c,
  required bool d,
  required bool e,
  required bool f,
}) {
  /*
		 a 
		 long
		 list
		 of 
		 comments
		 ...
		 ...

		 */

  print("Hello, world");
}
```

The viewing experience is suboptimal when scrolled down.
<img width="274" alt="Screenshot 2024-03-09 at 7 32 19 PM" src="https://github.com/nvim-treesitter/nvim-treesitter-context/assets/8187501/3c2eee00-aeb3-4f21-8fb1-2610edaaa819">

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim" 

### Expected behavior

It would be more desirable to have the first line of the function definition displayed ("`void main({`")

### Actual behavior

The last line of the function definition is displayed ("`}) {`"), which doesn't provide much useful information.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end
```

### Steps to reproduce

1. Use the code provided above.

**Comment by lewis6991** [comment]
This is an issue with the dart query.

We don't track issues with specific languages since no one owns them as they are community provided.

Will accept a PR that fixes any issues with dart.
