### ISSUE TITLE
Show ruby blocks in context

### ISSUE THREAD

**Issue by phallguy** [nvim-treesitter/nvim-treesitter-context#426]
Classes and methods work great, but ruby makes regular use of blocks that can sometimes grow unwieldy. It'd be nice if blocks could be included in the context as well.

Is there a configuration option to opt in other treesitter targets to be considered in the context bar? If not consider this a request for that feature.

 Thanks for the tool and appreciate the work already done on it.

**Comment by lewis6991** [comment]
Sorry but we don't take requests or track issues for any particular language.

PR's are welcome.

**Comment by phallguy** [comment]
Totally get that...but is there a config option to tell TS context which queries to use for showing context?

**Comment by lewis6991** [comment]
It just uses standard runtime search priority, see `:help 'runtimepath'`.  For injections, I place queries in my config directory `$XDG_CONFIG_HOME/nvim/queries`.

**Comment by alexsmartens** [comment]
@lewis6991 @phallguy could you elaborate on this solution?

are you taking about adding custom ruby queries, like this:
```scm
;.config/nvim/queries/ruby/locals.scm
(method name: (_) @method)
(module name: (_) @module)
(class name: (_) @class)
(def name: (_) @def)
(if)
(unless)
(case)
(when)
(for)
(while)
(until)
(do_block)
(begin)
(rescue)
(ensure)
(lambda)
(block)
(call)
``` 

along with adding ruby patterns?
```lua
-- .config/nvim/lua/plugins/treesitter-context.lua
...
patterns = {
  ruby = {
    "method",
    "module",
    "class",
    "def",
    "if",
    "unless",
    "case",
    "when",
    "for",
    "while",
    "until",
    "do_block",
    "begin",
    "rescue",
    "ensure",
    "lambda",
    "block",
    "call",
  },
},
```

That's what I did, [a commit to my dotfiles](https://github.com/alexsmartens/dotfiles/commit/d8cf91f3f8047313babede0a641b075041bfd549). I'm still missing something, could you chime in
