### ISSUE TITLE
height key must be positive integer error while scrolling down in markdown file when the first line is empty

### ISSUE THREAD

**Issue by seanbreckenridge** [nvim-treesitter/nvim-treesitter-context#431]
### Description

Scrolling down  in a markdown file when the first line is empty causes an error.

The error only appears once the first line is no longer visible

For context, originally I found this while using markdown files with yaml frontmatter, lke:

```markdown
---
title: something
---

# first title
```

... but seems to be the empty line (the fourth line in the code block above) that causes the issue.

### Neovim version

NVIM v0.10.0-dev-2946+g562719033e

### Expected behavior

No error when scrolling past the initial visible lines

### Actual behavior

When scrolling down, after each scroll, I get the following error:

```
Error detected while processing WinScrolled Autocommands for "*":
Error executing lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:51: 'height' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:51: in function 'display_window'
        ...vim-treesitter-context/lua/treesitter-context/render.lua:354: in function 'open'
        .../lazy/nvim-treesitter-context/lua/treesitter-context.lua:50: in function 'open'
        .../lazy/nvim-treesitter-context/lua/treesitter-context.lua:111: in function 'f'
        .../lazy/nvim-treesitter-context/lua/treesitter-context.lua:27: in function <.../lazy/nvim-treesitter-context/lua/treesitter-context.lua:21
```

https://github.com/nvim-treesitter/nvim-treesitter-context/assets/7804791/77135f24-e8c9-4f73-a812-5b1d748a126d

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

require'nvim-treesitter.configs'.setup {
  ensure_installed = { "markdown" },

  sync_install = true,

  highlight = {
    enable = true,
  }
}

-- copy pasted from the install snippet
require'treesitter-context'.setup{
  enable = true, -- Enable this plugin (Can be enabled/disabled later via commands)
  max_lines = 0, -- How many lines the window should span. Values <= 0 mean no limit.
  min_window_height = 0, -- Minimum editor window height to enable context. Values <= 0 mean no limit.
  line_numbers = true,
  multiline_threshold = 20, -- Maximum number of lines to show for a single context
  trim_scope = 'outer', -- Which context lines to discard if `max_lines` is exceeded. Choices: 'inner', 'outer'
  mode = 'cursor',  -- Line used to calculate context. Choices: 'cursor', 'topline'
  -- Separator between context and content. Should be a single character string, like '-'.
  -- When separator is set, the context will only show up when there are at least 2 lines above cursorline.
  separator = nil,
  zindex = 20, -- The Z-index of the context window
  on_attach = nil, -- (fun(buf: integer): boolean) return false to disable attaching
}
```

### Steps to reproduce

Have pushed the test files up to a repo here:

https://github.com/seanbreckenridge/treesitter-context-empty-line-bug/

1. `wget https://raw.githubusercontent.com/seanbreckenridge/treesitter-context-empty-line-bug/main/empty_space_broken.md https://raw.githubusercontent.com/seanbreckenridge/treesitter-context-empty-line-bug/main/minimal.lua`
2. `nvim --clean -u minimal.lua ./empty_space_broken.md`
3. scroll down so that the first line is no longer visible

This might require you to `:TSInstall markdown`, close `nvim` and then re-run the command in `2.`, Im not exactly sure how the order of that works.

If I remove the first line (the empty line) of the file in `./empty_space_broken.md`, the error no longer happens.

**Comment by jonahfang** [comment]
I also encountered this problem using the `nvim v0.10.0-dev-3007+GA736E845A`.

**Comment by cswingle** [comment]
I am also seeing this error with a Quarto markdown document where there is an empty line after the YAML header. For me, I get the messages after every scroll, regardless of what section of the file is displayed.

**Comment by MarioCarrion** [comment]
_For anyone looking for a workaround_

Having a fix for this would be ideal, but in the meantime if you want to disable it when you're editing markdown files you could do:

```lua
        vim.api.nvim_create_autocmd("FileType", {
            pattern = {"markdown"},
            callback = function(ev)
                require("treesitter-context").disable()
            end
        })
```

(Example above is assuming you're using lazy.nvim and it's called as part of `config` function)

Of course this means you are only editing markdown files and no other file types, otherwise it will be loaded no matter what.

**Comment by jonahfang** [comment]
@MarioCarrion Thanks!

**Comment by AngelBerihuete** [comment]
Also it can be disable in LazyVim

```python
return {
  -- disable nvim-treesitter-context
  { "nvim-treesitter/nvim-treesitter-context", enabled = false },
}
```
