### ISSUE TITLE
Q: is there a way to replicate GitHub's context?

### ISSUE THREAD

**Issue by s4my** [nvim-treesitter/nvim-treesitter-context#435]
To be clear, what I'm asking is if there is a way to ignore everything inside of a function scope. I don't care what if-statement or loop (while, for, loop, etc.) I am in; it is more useful to me to know what function I am in. I set my `max_lines = 1` for reference. e.g.:
```c
class TEST {
public:
    void test() {
        while (/* condition */) {
            if (/* condition */) {
                 // - If the CURSOR IS HERE, and I set `trim_scope = 'outer'`, the context shows `while (/* condition */) {` 
                 // - And if I set `trim_scope = 'inner'` the context show `class TEST{`
            }
        }
    }
};
```

**Comment by xzbdmw** [comment]
You can use your custom query(context.scm) to only contain function capture I think

**Comment by s4my** [comment]
@lewis6991 why did you close the issue without saying anything? if it's not possible you just say so.

**Comment by s4my** [comment]
> You can use your custom query(context.scm) to only contain function capture I think

I don't know match about queries, could you give an example

**Comment by lewis6991** [comment]
You got given an answer. You need to write queries. There are plenty of resources, in this repo and on the internet, of how to write them.

**Comment by s4my** [comment]
> You got given an answer. You need to write queries. There are plenty of resources, in this repo and on the internet of how to write them.

[xzbdmw](https://github.com/xzbdmw) finished his answer with "I think", which meant to me that maybe it's the answer or maybe it's not. It's just a suggestion to me. You don't have to be rude for no reason, sheeeesh

**Comment by youssef-lr** [comment]
have you figured this out? I'm looking for the same behavior as in VSCode which only shows the function name

**Comment by youssef-lr** [comment]
Ok I fixed it by making the cpp file like below:

<img width="790" alt="Screenshot 2024-09-03 at 15 53 27" src="https://github.com/user-attachments/assets/2f3dd92f-d3b0-4451-9d3f-354cf47b73b5">

But I had to actually modify the plugin's code in the `plugged` directory. Is there any other way to override it without touching the plugin's code? I believe once I update my changes will be removed

**Comment by youssef-lr** [comment]
too bad this didn't work :/ this is how TS queries can be overridden usually

<img width="253" alt="Screenshot 2024-09-03 at 16 10 50" src="https://github.com/user-attachments/assets/e4098b71-d984-4ee6-8caa-af0a6a303ef4">

**Comment by youssef-lr** [comment]
Oh nice, looks like a section was added to the docs that explain how to override queries https://github.com/nvim-treesitter/nvim-treesitter-context?tab=readme-ov-file#overriding-the-builtin-for-a-given-language
