### ISSUE TITLE
Error message when opening the command line window with q:

### ISSUE THREAD

**Issue by tyrdal** [nvim-treesitter/nvim-treesitter-context#437]
### Description

When I open the command line window with q: I get the following error message:

```
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:310: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
	[C]: in function 'nvim_win_close'
	...vim-treesitter-context/lua/treesitter-context/render.lua:310: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:308>
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:310: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
```

### Neovim version

0.9.5

### Expected behavior

If the context is not applicable then just don't run it there and avoid the error.

### Actual behavior

See description.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. TSInstall <whatever fits your file>
3. Make sure the setup functions have run for for treesitter and your plugin
4. Open a file that you installed a parser for in step 2
5. run q: in normal mode or hit : and follow it with crl+f

**Comment by lewis6991** [comment]
Unable to reproduce in nvim 0.10.0. Please check.

**Comment by rafamadriz** [comment]
> Unable to reproduce in nvim 0.10.0. Please check.

Having the same issue, I was able to reproduce with the minimal config provided on 0.9.5. You just have to make sure to enable treesitter-context. Here's an example:

https://asciinema.org/a/spFeVFBKRarvuKgyG5HtTIIxq

I also tried on 0.10 and there's no error, so it seems to be a 0.9.5 thing.

**Comment by lewis6991** [comment]
0.10 is release now, so don't need to fix this.
