### ISSUE TITLE
invaild node type in haskell

### ISSUE THREAD

**Issue by NamelessDev0000** [nvim-treesitter/nvim-treesitter-context#439]
### Description

Every time when I open a haskell in my neovim for the first time, nvim-treesitter-context will inform me that something was wrong:
![图片](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/61371380/aa9bf3f0-5932-41d4-908d-e45457171090)
but treesitter highlight works in a normal way...

### Neovim version

v9.5.0

### Actual behavior

just as what i mentioned in description...

### Minimal config

```Lua
default lazyvim, with normal haskell treesitter parser
```

### Steps to reproduce

this should be reproduce in any configuration.....

**Comment by lewis6991** [comment]
Queries need to be updated. We don't track issues for that.
