### ISSUE TITLE
Applying parsers to additional filetypes

### ISSUE THREAD

**Issue by LRitzdorf** [nvim-treesitter/nvim-treesitter-context#449]
I've noticed that when editing, for example, a shell script (filetype `sh`), no context lines are shown. However, manually changing the filetype to `bash` (for which this plugin lists explicit support) causes context to appear.

Is there a way of instructing this plugin (or the tree-sitter system at large?) to use certain parsers for filetypes other than their defaults? In my example, this would mean mapping the `sh` filetype to the `bash` parser.

Bears some superficial resemblance to #328.

**Comment by lewis6991** [comment]
I have `ft=sh` and contexts appear fine.

**Comment by lewis6991** [comment]
This plugin simply gets the parser via `vim.treesitter.get_parser(bufnr)`. If that doesn't work them the issue lies somewhere else.

**Comment by LRitzdorf** [comment]
Hm, I'll have to look into my config more deeply then. Thanks for the quick response!

As a side note, a throwaway script I typed up by hand failed to show context lines at all, with either `sh` or `bash` filetypes. This is definitely a "me" problem.
