### ISSUE TITLE
Parenthesis not highlighted in context

### ISSUE THREAD

**Issue by IbrahimARahman** [nvim-treesitter/nvim-treesitter-context#451]
<img width="1910" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter-context/assets/40009958/652ccd00-51d7-40bc-b97f-5aa3ad9184ee"><br />

This is how the context bars look in my nvim. Did some research on the issue but couldn't find anything. This also seems to apply to every language, not just typescript. I put my treesitter and context config below.

<img width="587" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter-context/assets/40009958/42c429ce-558a-4b1f-afa0-3850580d1250">

**Comment by lewis6991** [comment]
It's your colorscheme

**Comment by sthendev** [comment]
Thank you! Changing my `Delimiter` from `{ link = "Normal" }` to `{ fg = <my foreground color>, bg = "none" }` did the trick.
