### ISSUE TITLE
OCaml support doesn't work

### ISSUE THREAD

**Issue by last-genius** [nvim-treesitter/nvim-treesitter-context#458]
### Description

With the default setup, context is present in Lua files, C files and more. OCaml, despite declared support, doesn't work.

OCaml:
![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/53952748/0053b4fc-5440-4d33-b786-f0d7262bfcd4)

C:
![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/53952748/bb2a7e88-20ed-4259-bfbb-f971723d56e9)

### Neovim version

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068 

### Expected behavior

The context window showing up in OCaml files

### Actual behavior

Context window doesn't show up in OCaml files.

### Minimal config

```Lua
local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
  -- ADD ADDITIONAL PLUGINS THAT ARE _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Clone https://github.com/mirage/ocaml-ipaddr, for an example OCaml application
3. `nvim lib/ipaddr.ml`
4. Go to line 375, for example. Module should be showing up in the context window above. It isn't

**Comment by lewis6991** [comment]
Can you provide examples (not in screenshots), of code you expect to work?

**Comment by lewis6991** [comment]
Tried repro steps and works for me. Make sure the parser in installed.
