### ISSUE TITLE
Hidden files accidentally added?

### ISSUE THREAD

**Issue by itepechi** [nvim-treesitter/nvim-treesitter-context#462]
While updating my neovim plugins, I noticed that [this](https://github.com/nvim-treesitter/nvim-treesitter-context/commit/cc908326c93473041d44398d5ebfa2bb4169d649) commit adds 1.77 MB of vendor code and binaries, which is not very expected when the commit message is simply `docs: Update README.md`. Are these files added by accident, or are they there for something important?

**Comment by lewis6991** [comment]
Thanks, removed.
