### ISSUE TITLE
Language specific patterns are ignored

### ISSUE THREAD

**Issue by alexsmartens** [nvim-treesitter/nvim-treesitter-context#469]
### Description

I created this simple ruby class. `while` and `begin` nodes are correctly parsed by nodetree:
![Screenshot 2024-07-05 at 11 43 40 AM](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/26261714/53e49755-cb5e-4c64-aa4f-732391dfe72c)

However they are not kept in the top context window when I scroll down, only `def` is:
![Screenshot 2024-07-05 at 11 44 01 AM](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/26261714/ad6f52c4-ff74-4d0a-a96e-f462ea677309)

### Neovim version

v0.10.0

### Expected behavior

 `while` and `begin` would be kept in the top context window.

### Actual behavior

 `while` and `begin` are  not kept in the top context window.

### Minimal config

```Lua
return {
  {
    "nvim-treesitter/nvim-treesitter-context",
    config = function()
      require "treesitter-context".setup {
        enable = true,
        max_lines = 0,
        min_window_height = 0,
        line_numbers = true,
        multiline_threshold = 10,
        trim_scope = "outer",
        mode = "cursor",
        separator = nil,
        zindex = 20,
        patterns = {
          default = {
            "class",
            "function",
            "method",
            "for",
            "while",
            "if",
            "switch",
            "case",
          },
          ruby = {
            "method",
            "module",
            "class",
            "def",
            "if",
            "unless",
            "case",
            "when",
            "for",
            "while",
            "until",
            "do_block",
            "begin",
            "rescue",
            "ensure",
            "lambda",
            "block",
            "call",
          },
        },
      }
    end,
  },
}
```

### Steps to reproduce

Create:
```
# best_model.rb
class BestModel
  def very_long_method
    i = 10
    while i < 10
      begin
        i += 1
















      rescue StandardError => exception
        puts "erros"
      end
    end
  end
end
```

Scroll down, notice  `while` and `begin` are  not kept in the top context window.

**Comment by lewis6991** [comment]
patterns aren't a part of this plugin anymore. You need to define queries.
