### ISSUE TITLE
How to prevent trimming of the context as I scroll up?

### ISSUE THREAD

**Issue by justinas** [nvim-treesitter/nvim-treesitter-context#471]
Hey,

First of all, sorry if this issue has been filed before: I'm not familiar with the terminology for my problem, so I might have missed something when searching existing issues. https://github.com/nvim-treesitter/nvim-treesitter-context/issues/425 might be similar, but I'm not sure.

I'm currently using context-vim. As I scroll up and my cursor reaches the context pane, the context does not disappear, instead the main pane's viewport is scrolled and the entire context is kept (ignoring the fact that context-vim does not include the multi-line function parameters):

[![asciicast](https://asciinema.org/a/nQsJheN8dEacATNpDAlKe1MOA.svg)](https://asciinema.org/a/nQsJheN8dEacATNpDAlKe1MOA)

With nvim-treesitter-context however, as my cursor reaches the edge between the context pane and the main pane, I start losing context. This is with `trim_scope = 'inner'`, but with outer I'd still be losing lines of context, just starting from the other end.

[![asciicast](https://asciinema.org/a/3lzdN0SnziGVNBL2Of5yQeIoE.svg)](https://asciinema.org/a/3lzdN0SnziGVNBL2Of5yQeIoE)

Is it possible to have the behavior equivalent to `context-vim` here, where the entire context is kept?

**Comment by lewis6991** [comment]
Set `scrolloff` to something.

**Comment by justinas** [comment]
> Set `scrolloff` to something.

Right, setting `scrolloff=3` seems to keep 3 lines of context as I scroll up. This is not exactly what I'm looking for though - is there a way to display all the context at any time, other than setting scrolloff to a very large number?

**Comment by lewis6991** [comment]
No.

**Comment by samuelsimoes** [comment]
First, thank you for the effort you put into the extension. It's really helpful.

I was about to create the same issue — I'm also missing the context.vim behavior.

When I scroll up close to the upper edge and the context line starts to disappear, I kind of get a bit lost because the context information is no longer visible.

**Comment by lewis6991** [comment]
Sorry, this behaviour won't be added. Please set `scrolloff`.
