### ISSUE TITLE
Context doesn't work automatically, needs manual enabling

### ISSUE THREAD

**Issue by datcit241** [nvim-treesitter/nvim-treesitter-context#474]
### Description

When I launch nvim with a file, the plugin doesn't work if navigating with `i`, and `k`, but it does when navigating with `<C-d>` and `<C-u>`. 
Additionally, when I open a new buffer, it doesn't work at all.
So, I have to manually run `:TSContextEnable` when opening any files in a buffer in order to get it to work.

### Neovim version

NVIM v0.10.0, Build type: Release, LuaJIT 2.1.1713484068

### Expected behavior

Works automatically in any opened buffer with `i`, `k`, `<C-d>` and `<C-u>` navigation.

### Actual behavior

- Only works with `<C-d>` and `<C-u>` in the first buffer
- Doesn't work in the subsequent buffers 

### Minimal config

```Lua
{
  "nvim-treesitter/nvim-treesitter-context",
  lazy = true,
  cmd = { "TSContextEnable", "TSContextDisable", "TSContextToggle" },
  event = "VeryLazy",
  opts = {
    enable = true,
  }
}
```

### Steps to reproduce

1. `nvim index.js`
2. Only works with `<C-d>` and `<C-u>` navigations
3. Open another file in a new buffer
4. Doesn't work for that file

**Comment by lewis6991** [comment]
Remove `cmd`, `event` and `lazy`.

**Comment by lewis6991** [comment]
The plugin does work. Something is probably wrong with your config.

**Comment by datcit241** [comment]
Can you kindly demonstrate that it's working properly in a react project? It's not just something is wrong with my config, I guess.

**Comment by lewis6991** [comment]
Emm no! This isn't some free support service.

**Comment by datcit241** [comment]
Lol, that's not how open-source development works, and it won't make the community great as there is a bug and other people may encounter that bug too and you come and say nah it works there's something wrong with your config, and you can literally say that to any open nvim plugin issues ever I believe.
Fine, I'm gonna use a bare minimal config to prove you are nothing but a nay-sayer.

**Comment by lewis6991** [comment]
> Lol, that's not how open-source development works

I do not think you have any idea how open source works.

It does **NOT** work by asking people to spend their time on **YOUR** problems.

You've raised an issue with some obviously broken config expecting help.

If you understood open source, you would have debugged and fixed the issue yourself (if one exists), and raised a PR. Otherwise, you would have provided enough evidence that there is an actual issue.

If there really was an issue like the one you are describing, firstly CI would fail, but there would also be more people reporting this, and I would probably be able to trivially reproduce it.

> Fine, I'm gonna use a bare minimal config to prove you are nothing but a nay-sayer.

You should have done that to begin with.

Please don't use this plugin. I don't want you as a user.

**Comment by datcit241** [comment]
For those who are using Nvchad, I figured out by default NvChad doesn't work with this plugin meanwhile Lazyvim does, and I'm using Nvchad.

> Please don't use this plugin. I don't want you as a user.
Well, I won't at least until I can figure out how to make this work.

**Comment by Jean-CS** [comment]
@lewis6991 @datcit241 

Looks like the fix for NvChad here is using `event = "VeryLazy"`

```lua
  {
    "nvim-treesitter/nvim-treesitter-context",
    event = "VeryLazy",
    opts = {
      enable = true, -- Enable this plugin (Can be enabled/disabled later via commands)
      ...
    },
  },
```

**Comment by sai-sy** [comment]
@Jean-CS, your solution works for me on NvChad! Without `VeryLazy`, it doesn't work; with it, it does! But now I always get  
`Failed to run 'config' for nvim-treesitter-context

.../lazy/nvim-treesitter-context/lua/treesitter-context.lua:166: Invalid 'event': 'LspRequest'`

Still works thought. Have you faced the same issue with your NVChad setup and how'd you get around that?
