### ISSUE TITLE
Filter blank and comment-only lines from context view

### ISSUE THREAD

**Issue by snoblenet** [nvim-treesitter/nvim-treesitter-context#476]
It would be great if this tool could filter blank and comment-only lines from the context view.

At present, with `multiline_threshold = 3`, I see this:

![image](https://github.com/user-attachments/assets/76f1e07d-00d6-4f66-add7-3955f2eb60a7)

It would be great if the tool could either filter this down the single relevant line of context (`if vim.g.neovide then`), or use this as an opportunity to display a second relevant line that is currently not shown, like this:

```
callback = function()
  if vim.g.neovide then
```

**Comment by lewis6991** [comment]
This will overcomplicate the implementation.

You may be able to fix this by changeing the query.

**Comment by Crypto-Spartan** [comment]
> You may be able to fix this by changing the query.

@lewis6991 could you point me in a direction on how to do this? Based on the options exposed via the `setup()` function, I'm not sure how to approach this.

**Comment by Crypto-Spartan** [comment]
@snoblenet I have a partial fix for this. I modified the `queries/lua/context.scm` file to fix function definitions and if statements.

Follow the guide on the [README to override the builtin for a given language](https://github.com/nvim-treesitter/nvim-treesitter-context/tree/3d5390c49e3f8fe457b376df2a49aa39d75b7911?tab=readme-ov-file#overriding-the-builtin-for-a-given-language). Create a `context.scm` file for lua.

Paste this in:

```
(for_statement
  body: (_) @context.end
) @context

(while_statement
  body: (_) @context.end
) @context

(do_statement
  body: (_) @context.end
) @context

(function_definition
  parameters: (_)
  _ @context.end
) @context

(table_constructor
  (_) @context.end
) @context

(function_declaration
  parameters: (_) @context.final
) @context

(if_statement
  consequence: (_) @context.end
) @context

(if_statement
  (comment _) @context.end
) @context

(repeat_statement
  body: (_) @context.end
)  #@context
```

Just a few modifications to the default query file will fix this issue. I personally don't see how "this will overcomplicate the implementation".

**Comment by lewis6991** [comment]
The implementation is the Lua code. I wasn't sure if this could be done just in the query.

**Comment by Crypto-Spartan** [comment]
@lewis6991 Can you explain the difference between @context.end vs @context.final?

**Comment by lewis6991** [comment]
`@context.end` is exclusive, `@context.final` is inclusive.

**Comment by samox73** [comment]
> This will overcomplicate the implementation.
> 
> You may be able to fix this by changing the query.

Comments in code are common and the lack of this feature drastically reduces the plugins usefulness for its designed purpose.

**Comment by lewis6991** [comment]
No. This should be handled by the queries. Each language has a different comment style; so you won't be able to implement this properly without doing it via queries.

Please refrain from commenting on issues with strong opinions if you don't understand the technical details. It unnecessarily pings people and wastes their time.

**Comment by samox73** [comment]
How do you want to foster constructive collaboration while denying people without technical expertise on the matter access to discussions? The default queries are part of this plugin. I'm saying that the queries for the respective languages should exclude comments by default. I have tried the example provided by @Crypto-Spartan for lua code, which works as expected. If you don't agree that the default behavior should exclude comments, that's fine. I'm just saying that I have a different opinion on the matter.

**Comment by lewis6991** [comment]
> I'm saying that the queries for the respective languages should exclude comments by default.

Queries are strictly community supported (see: https://github.com/nvim-treesitter/nvim-treesitter-context/blob/master/README.md#supported-languages)

> How do you want to foster constructive collaboration while denying people without technical expertise on the matter access to discussions?

I don't. Maintaining this project as open source is a burden that I get nothing from. I have zero bandwidth, nor motivation to hand hold anyone.

>  I have tried the example provided by @Crypto-Spartan for lua code, which works as expected. If you don't agree that the default behavior should exclude comments, that's fine. I'm just saying that I have a different opinion on the matter.

Anyone is free to raise a PR to fix this, but it has to be a query change, not a change to the Lua code, and has to be done for each language individually.

> I'm just saying that I have a different opinion on the matter.

No one asked for your opinion. This isn't a town hall.
