### ISSUE TITLE
An error occurs when opening the command-line window

### ISSUE THREAD

**Issue by archilkarchava** [nvim-treesitter/nvim-treesitter-context#507]
### Description

To reproduce try to open the command-line window, e.g. by pressing `q:` in normal mode when the context is shown.

### Neovim version

0.10.2

### Expected behavior

No error should be shown.

### Actual behavior

The following error is shown when opening the command-line window:
Error executing vim.schedule lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:302: E11: Invalid in command-line window; <CR> executes, 
CTRL-C quits                                                                                                                                                    
stack traceback:                                                                                                                                                
        [C]: in function 'nvim_buf_delete'                                                                                                                      
        ...vim-treesitter-context/lua/treesitter-context/render.lua:302: in function <...vim-treesitter-context/lua/treesitter-context/render.lua:296>          

### Minimal config

local plugins = {
  ts         = 'https://github.com/nvim-treesitter/nvim-treesitter',
  ts_context = 'https://github.com/nvim-treesitter/nvim-treesitter-context',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.o.runtimepath = install_path..','..vim.o.runtimepath
end

### Steps to reproduce

1. `nvim --clean -u minimal.lua treesitter-context.lua` (you can replace the `treesitter-context.lua` with any other large enough file where the context will be shown).
2. Move the cursor down until the context appears.
3. Press `q:` in normal mode to enter the command-line window mode.

https://github.com/user-attachments/assets/3e866dd5-1f29-4d8d-94f9-77d490ca7d08

**Comment by lewis6991** [comment]
@apollo1321 could this be from one of your recent changes?
