### ISSUE TITLE
Incorrect context when using Java annotations

### ISSUE THREAD

**Issue by minhduc0711** [nvim-treesitter/nvim-treesitter-context#53]
I expect to see the method line instead of `@Override`. Not sure if this is related to your plugin or Treesitter tho.

https://user-images.githubusercontent.com/34294427/121860909-855dd280-cd23-11eb-9686-4d3eb9f7ec39.mp4

**Comment by romgrk** [comment]
Oh yes, that's multi-line definitions being buggy again. If the java TS parser marks the decorators as part of the function node, it should be solved by debugging the multi-line nodes. I'll try to look at it soon.

**Comment by cshjsc** [comment]
Hi, any updates on this?

**Comment by lewis6991** [comment]
> Hi, any updates on this?

No

**Comment by lewis6991** [comment]
With #198, Java is no longer supported. Will happily accept a PR that adds support.
