### ISSUE TITLE
How to manually attach to buffer in a float window?

### ISSUE THREAD

**Issue by ibhagwan** [nvim-treesitter/nvim-treesitter-context#534]
Since the introduction of `multiwindow` I'm trying to attach the context to a fzf-lua  preview window float, after a quick glance at the code this is what I came up with but it doesn't seem to do anything:
```lua
function Previewer.base:update_ts_context()
  -- excerpt from nvim-treesitter-context `update_single_context`
  if not package.loaded["treesitter-context"] then return end
  local bufnr, winid = self.preview_bufnr, self.win.preview_winid
  require("treesitter-context.render").close_leaked_contexts()
  local context_ranges, context_lines = require("treesitter-context.context").get(bufnr, winid)
  if not context_ranges or #context_ranges == 0 then
    require("treesitter-context.render").close(winid)
    return
  end
  assert(context_lines)
  require("treesitter-context.render").open(bufnr, winid, context_ranges, context_lines)
  -- _G.dump("ts", bufnr, winid, context_ranges, context_lines)
end
```

Inspecting the `context_ranges` and `context_lines` tables seem to have the correct context (relative to the preview window cursor line), but the rendering doesn't seem to do anything eventhough the `open` call finishes succesfully.

My setup call is a simple:
```lua
require("treesitter-context").setup({ enable = true, multiwindow = true })
``

Any pointers would be greatly appreciated.

**Comment by lewis6991** [comment]
These functions aren't API.

**Comment by lewis6991** [comment]
That sounds like feature creep.

**Comment by ibhagwan** [comment]
> These functions aren't API.

I know, that’s why I’m asking.

> That sounds like feature creep.

To each their own, imagine you just searched and have a lot of matches which you’re reviewing and you find yourself scrolling the preview up to understand if the match is part of which function, sounds very reasonable to me.

I don’t think the effort is that big from having `multiwindow` to having the ability to manually control a window by number? The functions are already there, just a matter of exposing it or having `:TSContexf enable <winid>`.

**Comment by lewis6991** [comment]
Maybe you can fork this plugin, implement the features you want and continue to support and maintain it? Sounds reasonable to me.

**Comment by ibhagwan** [comment]
@lewis6991 will you a PR? If so I’ll gladly submit one.
