### ISSUE TITLE
Show `protected:`, `public:` and `private:` as context for c++

### ISSUE THREAD

**Issue by IndianBoy42** [nvim-treesitter/nvim-treesitter-context#59]
This might require/want having a different list of nodes to use as context for each language (with the current patterns as the common default)

Maybe a more general mechanism would also be to let the user customized which nodes count as context nodes

**Comment by romgrk** [comment]
Seems a bit involved for this plugin, starts to feel like it's more of an LSP responsability. I'm not opposed to having it in the plugin but I don't have enough time and interest to implement, PR welcome.
