### ISSUE TITLE
Closest node not added to context at correct time

### ISSUE THREAD

**Issue by camgraff** [nvim-treesitter/nvim-treesitter-context#76]
![Peek 2021-10-31 21-32](https://user-images.githubusercontent.com/46980357/139614162-df23047c-3034-4800-bbdc-cf0524d00ea8.gif)

In the gif, I hit `j` 3 times before the last node is added to the context. I expect it would be added after the first `j`. It looks like the context update does not account for farther nodes obscuring some visible lines.

**Comment by lewis6991** [comment]
Can you confirm if this is still an issue?

**Comment by camgraff** [comment]
Looks like it's not anymore!
