### ISSUE TITLE
Markdown heading context

### ISSUE THREAD

**Issue by axieax** [nvim-treesitter/nvim-treesitter-context#87]
Hi!
Now that Treesitter supports Markdown, does anyone know how to enable nvim-treesitter-context for Markdown headings (`atx-heading`)? It seems like the following config doesn't work (probably because heading content isn't nested):
```lua
require("treesitter-context").setup({
  patterns = {
    markdown = { "atx_heading" }
  }
)}
```

**Comment by romgrk** [comment]
If the nodes aren't nested, then the plugin currently doesn't support adding a context.

It would be possible to implement, but it would require some work.

**Comment by axieax** [comment]
Fair enough, might be better holding this one out as a potential feature some time in the future :)

**Comment by lewis6991** [comment]
If the content isn't nested then this is not feasible for us to support (especially for just one language).
